# ==========================================
# “A Station”服务器属性:
# "A Station" Server Properties:
# ==========================================

# “A Station”服务器 ID
# "A Station" Server Id
# 默认值: 2 / Default : 2
a.station.server.id = 2

# 允许进入 “A Station” 服务器的最高等级
# Maximum Level to "A Station" Server Authorization
# 默认值: 75 / Default : 75
# 自定义: 83 / Custom: 83
a.station.max.level = 83

# 启用 “A Station” 服务器
# Enable "A Station" Server
a.station.enable = false
