# ==========================================
# 欧比斯登陆配置:
# Abyss Landing config's:
# ==========================================
# ==========================================
# [启用任务点数重置]
# [Reset Quest Point Enable]
# ==========================================
# 默认值: true / Default: true
gameserver.landing.quest.reset.enable = true

# ==========================================
# [任务点数重置时间]
# [Quest Point Reset Time]
# ==========================================
# 默认值: 0 0 12 ? * MON * / Default: 0 0 12 ? * MON *
gameserver.landing.quest.reset.time = 0 0 12 ? * MON *

# ==========================================
# [启用欧比斯登陆点数重置]
# [Abyss Landing Reset Point Enable]
# ==========================================
# 默认值: false / Default: false
gameserver.landing.points.reset.enable = true

# ==========================================
# [欧比斯登陆点数重置时间]
# [Abyss Landing Point Reset Time]
# ==========================================
# 默认值: 0 0 0 ? * MON * / Default: 0 0 0 ? * MON *
gameserver.landing.points.reset.time = 0 0 0 ? * MON *

# ==========================================
# [任务点数倍率]
# [Quest Point Rate]
# ==========================================
# 默认值: 1 / Default: 1
gameserver.landing.quest.rate = 1
