# ==========================================
# AI 相关配置:
# AI config's:
# ==========================================

# 调试（供开发者使用）
# Debug (for developers)
gameserver.ai.move.debug = true
gameserver.ai.event.debug = false
gameserver.ai.oncreate.debug = false

# 与生物的等级差达到该值时免疫仇恨
# Level difference with the creature to be immune to aggro
gameserver.ai.aggro.level.immune = 10

# 启用 NPC 移动
# Enable NPC movement
gameserver.npcmovement.enable = true

# NPC 再次移动前的最短等待时间（秒）。
# The minimum time in seconds that the NPC waits before moving again.
# 默认值: 3（秒） / Default: 3 (seconds)
gameserver.npcmovement.delay.minimum = 3

# NPC 再次移动前的最长等待时间（秒）。
# The maximum time in seconds that the NPC waits before moving again.
# 默认值: 15（秒） / Default: 15 (seconds)
gameserver.npcmovement.delay.maximum = 15

# NPC 喊话开关
# Npc Shouts activator
gameserver.npcshouts.enable = false
