# 自动组队配置
# ==========================================
# 自动组队配置 / AUTO GROUP CONFIG:
# ==========================================

# 启用自动组队
# Enable Auto Group
# 默认值: true / Default: true
gameserver.autogroup.enable = true

# ==========================================
# 钢铁之战 / Dredgion:
# ==========================================
# 启用钢铁之战副本
# Enable Dredgion instance
# 默认值: true / Default: true
gameserver.dredgion.enable = true

# 钢铁之战报名时间
# Dredgion Registration Time
# 默认值: 60 分钟 / Default: 60 min
gameserver.dredgion.timer = 60

# 钢铁之战进入时间
# Dredgion Time Entry
# 中午: 0 0 12 ? * MON,TUE,WED,THU,FRI,SAT,SUN * / Midday: 0 0 12 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
# 傍晚: 0 0 20 ? * MON,TUE,WED,THU,FRI,SAT,SUN * / Evening: 0 0 20 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
# 午夜: 0 0 23 ? * MON,TUE,WED,THU,FRI,SAT,SUN * / Midnight: 0 0 23 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
gameserver.dredgion.schedule.midday = 0 0 12 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
gameserver.dredgion.schedule.evening = 0 0 20 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
gameserver.dredgion.schedule.midnight = 0 0 23 ? * MON,TUE,WED,THU,FRI,SAT,SUN *

# ==========================================
# 卡玛尔战场 4.3 / Kamar Battlefield 4.3:
# ==========================================
# 启用卡玛尔战场 4.3
# Enable Kamar Battlefield 4.3
# 默认值: true / Default: true
gameserver.kamar.enable = true

# 卡玛尔战场 4.3 报名
# Kamar Battlefield 4.3 Registration.
# 默认值: 60 分钟 / Default: 60 min
gameserver.kamar.timer = 60

# 卡玛尔战场 4.3 进入时间
# Kamar Battlefield 4.3 Time Entry
# 午夜: 0 0 23 ? * FRI * / Midnight: 0 0 23 ? * FRI *
gameserver.kamar.schedule.midnight = 0 0 23 ? * FRI *

# ==========================================
# 被吞噬的奥菲丹桥 4.5 / Engulfed Ophidan Bridge 4.5:
# ==========================================
# 启用被吞噬的奥菲丹桥 4.5
# Enable Engulfed Ophidan Bridge 4.5
# 默认值: false / Default: false
gameserver.ophidan.enable = true

# 被吞噬的奥菲丹桥 4.5 报名
# Engulfed Ophidan Bridge 4.5 Registration.
# 默认值: 60 分钟 / Default: 60 min
gameserver.ophidan.timer = 60

# 被吞噬的奥菲丹桥 4.5 进入时间
# Engulfed Ophidan Bridge 4.5 Time Entry
# 中午: 0 0 12 ? * TUE,THU,SAT * / Midday: 0 0 12 ? * TUE,THU,SAT *
# 午夜: 0 0 23 ? * TUE,THU,SAT * / Midnight: 0 0 23 ? * TUE,THU,SAT *
gameserver.ophidan.schedule.midday = 0 0 12 ? * TUE,THU,SAT *
gameserver.ophidan.schedule.midnight = 0 0 23 ? * TUE,THU,SAT *

# ==========================================
# 铁壁战线 4.5 / Iron Wall Warfront 4.5:
# ==========================================
# 启用铁壁战线 4.5
# Enable Iron Wall Warfront 4.5
# 默认值: false / Default: false
gameserver.bastion.enable = true

# 铁壁战线 4.5 报名
# Iron Wall Warfront 4.5 Registration.
# 默认值: 60 分钟 / Default: 60 min
gameserver.bastion.timer = 60

# 铁壁战线 4.5 进入时间
# Iron Wall Warfront 4.5 Time Entry
# 午夜: 0 0 23 ? * FRI * / Midnight: 0 0 23 ? * FRI *
gameserver.bastion.schedule.midnight = 0 0 23 ? * FRI *

# ==========================================
# 伊迪安穹顶 4.7 / Idgel Dome 4.7:
# ==========================================
# 启用伊迪安穹顶 4.7
# Enable Idgel Dome 4.7
# 默认值: false / Default: false
gameserver.idgel.dome.enable = true

# 伊迪安穹顶 4.7 报名
# Idgel Dome 4.7 Registration.
# 默认值: 60 分钟 / Default: 60 min
gameserver.idgel.dome.timer = 60

# 伊迪安穹顶 4.7 进入时间
# Idgel Dome 4.7 Time Entry
# 中午: 0 0 12 ? * MON,WED,FRI * / Midday: 0 0 12 ? * MON,WED,FRI *
# 午夜: 0 0 23 ? * MON,WED,FRI * / Midnight: 0 0 23 ? * MON,WED,FRI *
gameserver.idgel.dome.schedule.midday = 0 0 12 ? * MON,WED,FRI *
gameserver.idgel.dome.schedule.midnight = 0 0 23 ? * MON,WED,FRI *

# ==========================================
# 阿修纳塔尔钢铁之战 5.1 / Ashunatal Dredgion 5.1:
# ==========================================
# 启用阿修纳塔尔钢铁之战 5.1
# Enable Ashunatal Dredgion 5.1
# 默认值: false / Default: false
gameserver.ashunatal.dredgion.enable = true

# 阿修纳塔尔钢铁之战 5.1 报名
# Ashunatal Dredgion 5.1 Registration.
# 默认值: 60 分钟 / Default: 60 min
gameserver.ashunatal.dredgion.timer = 60

# 阿修纳塔尔钢铁之战 5.1 进入时间
# Ashunatal Dredgion 5.1 Time Entry
# 中午: 0 0 12 ? * MON,TUE,WED,THU,FRI,SAT,SUN * / Midday: 0 0 12 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
# 傍晚: 0 0 20 ? * MON,TUE,WED,THU,FRI * / Evening: 0 0 20 ? * MON,TUE,WED,THU,FRI *
# 午夜: 0 0 23 ? * SAT,SUN * / Midnight: 0 0 23 ? * SAT,SUN *
gameserver.ashunatal.schedule.midday = 0 0 12 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
gameserver.ashunatal.schedule.evening = 0 0 20 ? * MON,TUE,WED,THU,FRI *
gameserver.ashunatal.schedule.midnight = 0 0 23 ? * SAT,SUN *

# ==========================================
# 奥菲丹战径 5.1 / Ophidan Warpath 5.1:
# ==========================================
# 启用奥菲丹战径 5.1
# Enable Ophidan Warpath 5.1
# 默认值: false / Default: false
gameserver.ophidan.warpath.enable = true

# 奥菲丹战径 5.1 报名
# Ophidan Warpath 5.1 Registration.
# 默认值: 60 分钟 / Default: 60 min
gameserver.ophidan.warpath.timer = 60

# 奥菲丹战径 5.1 进入时间
# Ophidan Warpath 5.1 Time Entry
# 午夜: 0 0 23 ? * TUE,THU * / Midnight: 0 0 23 ? * TUE,THU *
gameserver.ophidan.warpath.schedule.midnight = 0 0 23 ? * TUE,THU *

# ==========================================
# 伊迪安穹顶地标 5.1 / Idgel Dome Landmark 5.1:
# ==========================================
# 启用伊迪安穹顶地标 5.1
# Enable Idgel Dome Landmark 5.1
# 默认值: false / Default: false
gameserver.idgel.dome.landmark.enable = true

# 伊迪安穹顶地标 5.1 报名
# Idgel Dome Landmark 5.1 Registration.
# 默认值: 60 分钟 / Default: 60 min
gameserver.idgel.dome.landmark.timer = 60

# 伊迪安穹顶地标 5.1 进入时间
# Idgel Dome Landmark 5.1 Time Entry
# 午夜: 0 0 23 ? * MON,WED * / Midnight: 0 0 23 ? * MON,WED *
gameserver.idgel.dome.landmark.schedule.midnight = 0 0 23 ? * MON,WED *

# ==========================================
# 坚韧之厅 5.3 / Hall Of Tenacity 5.3:
# ==========================================
# 启用坚韧之厅 5.3
# Enable Hall Of Tenacity 5.3
# 默认值: false / Default: false
gameserver.hall.of.tenacity.enable = true

# 坚韧之厅 5.3 报名
# Hall Of Tenacity 5.3 Registration.
# 默认值: 6 小时 / Default: 6H
# 官服开放时长: 6 小时
# Official stay open: 6H
gameserver.hall.of.tenacity.timer = 360

# 坚韧之厅 5.3 进入时间
# Hall Of Tenacity 5.3 Time Entry
# 上午: 0 0 9 ? * SAT,SUN * / Morning: 0 0 9 ? * SAT,SUN *
# 傍晚: 0 0 18 ? * MON,TUE,WED,THU,FRI * / Evening: 0 0 18 ? * MON,TUE,WED,THU,FRI *
gameserver.hall.of.tenacity.schedule.morning = 0 0 9 ? * SAT,SUN *
gameserver.hall.of.tenacity.schedule.evening = 0 0 18 ? * MON,TUE,WED,THU,FRI *

# ==========================================
# 大竞技场训练营 5.6 / Grand Arena Training Camp 5.6:
# ==========================================
# 启用大竞技场训练营 5.6
# Enable Grand Arena Training Camp 5.6
# 默认值: false / Default: false
gameserver.grand.arena.training.camp.enable = true

# 大竞技场训练营 5.6 报名
# Grand Arena Training Camp 5.6 Registration.
# 默认值: 6 小时 / Default: 6H
# 官服开放时长: 6 小时
# Official stay open: 6H
gameserver.grand.arena.training.camp.timer = 360

# 大竞技场训练营 5.6 进入时间
# Grand Arena Training Camp 5.6 Time Entry
# 傍晚: 0 0 18 ? * SAT,SUN * / Evening: 0 0 18 ? * SAT,SUN *
gameserver.grand.arena.training.camp.schedule.evening = 0 0 18 ? * SAT,SUN *

# ==========================================
# IDRun 5.8:
# ==========================================
# 启用 IDRun 5.8
# Enable IDRun 5.8
# 默认值: false / Default: false
gameserver.IDRun.enable = true

# IDRun 5.8 报名
# IDRun 5.8 Registration.
# 默认值: 6 小时 / Default: 6H
# 官服开放时长: 1 小时
# Official stay open: 1H
gameserver.IDRun.timer = 60

# IDRun 5.8 进入时间
# IDRun 5.8 Time Entry
gameserver.IDRun.schedule = 0 0 0/2 1/1 * ? *
