# ==========================================
# “经纪人”属性:
# "Broker" Properties:
# ==========================================
# 将经纪人数据保存到数据库的间隔（秒）
# Time in seconds for saving broker data into the DB
# 默认值....: 6s / Default....: 6s
# 标准......: 8s / Standard...: 8s
# 专业......: 10s / Pro........: 10s
gameserver.broker.save.manager.interval = 6

# 检查经纪人过期物品并退回玩家邮箱的间隔（秒）
# Time in seconds for checking broker expired items and sending back to user's mail box
# 默认值....: 60s / Default....: 60s
# 标准......: 35s / Standard...: 35s
# 专业......: 20s / Pro........: 20s
gameserver.broker.time.check.expired.items.interval = 60

# 处罚
# Punishment
# 0 - 仅记录日志 / add log record
# 1 - 记录日志并踢出玩家 / log and kick player from game
gameserver.broker.anti.hack.punishment = 0

# 经纪人物品多少天后标记为过期
# How many days should pass for broker items to mark as a expired items
# 默认值: 8 天 / Default: 8-days
gameserver.broker.items.expire.time = 8
