# ==========================================
# 数据库清理配置:
# Database Cleaning config's:
# ==========================================

# 启用数据库清理
# Enable Database Cleaning
# 默认值: false / Default: false
gameserver.cleaning.enable = false

# 非活跃角色被删除的周期
# Period after which inactive chars get deleted
# 以天数表示
# It is expressed in number of days
# 该值低于 30 时不会执行清理
# Cleaning won't be executed with a value lower than 30
# 默认值: 180 / Default: 180
gameserver.cleaning.period = 180

# 执行清理的线程数
# Number of threads executing the cleaning
# 若待删除角色很多，建议使用 4 到 6
# If you have many chars to delete you should use a value between 4 and 6
# 默认值: 2 / Default: 2
gameserver.cleaning.threads = 2

# 单次执行删除的最大角色数量
# Maximum amount of chars deleted at one execution
# 若一次删除过多角色，数据库会严重碎片化，从而大幅增加运行时间
# If too many chars are deleted in one run your database will
# get strongly fragmented which increases runtime dramatically
# 注意：0 表示不限制
# Note: 0 for not limitation
# 默认值: 5000 / Default: 5000
gameserver.cleaning.limit = 5000

# ----------------------------
# 欧比斯排名清理配置:
# Abyss Rank Cleaning config's:
# ----------------------------
# 启用欧比斯排名清理
# Enable Abyss Rank Cleaning
# 默认值: false / Default: false
gameserver.abyss.cleaning.enable = false

# 欧比斯排名被删除的周期
# Period after which abyss rank get deleted
# 以天数表示
# It is expressed in number of days
# 该值低于 30 时不会执行清理
# Cleaning won't be executed with a value lower than 30
# 默认值: 180 / Default: 180
gameserver.abyss.cleaning.period = 180
