# ==========================================
# 公共相关配置:
# Commons config's:
# ==========================================

# 启用 Runnable 执行统计收集
# Enable gathering execution stats of runnables
# 默认值: true / Default: true
commons.runnablestats.enable = true
