# 活动配置
#======================#
#======  活动 EVENT  =======#
#======================#
# 启用活动
# Enable event
# 默认值: false / Default: false
gameserver.event.enable = true

# ==========================================
# 活动装饰 / Event Decor
# ==========================================
# 0 = 无装饰 / No Decorations
# 1 = 圣诞节 / Christmas
# 2 = 万圣节 / Halloween
# 3 = 万圣节 + 圣诞节 / Halloween + Christmas
# 4 = 情人节 / Valentine
# 5 = 情人节 + 圣诞节 / Valentine + Christmas
# 6 = 情人节 + 万圣节 / Valentine + Halloween
# 7 = 情人节 + 圣诞节 + 万圣节 / Valentine + Christmas + Halloween
# 8 = 夏日泼水节 / Water Splash Summer
# 9 = 夏日泼水节 + 圣诞节 / Water Splash Summer + Christmas
# 10 = 春节 / Chinese New Year
# 11 = 春节 + 圣诞节 / Chinese New Year + Christmas
# 12 = 春节 + 万圣节 / Chinese New Year + Hallowen
# 13 = 春节 + 圣诞节 + 万圣节 / Chinese New Year + Christmas + Hallowen
# 14 = 春节 + 情人节 / Chinese New Year + Valentine
# 15 = 春节 + 圣诞节 + 情人节 / Chinese New Year + Christmas + Valentine
# 16 = 春节 + 万圣节 + 情人节 / Chinese New Year + Halloween + Valentine
# 17 = 春节 + 万圣节 + 情人节 + 圣诞节 / Chinese New Year + Halloween + Valentine + Christmas
# 18 = 春节 + 夏日泼水节 / Chinese New Year + Water Splash Summer
# 19 = 春节 + 圣诞节 + 夏日泼水节 / Chinese New Year + Christmas + Water Splash Summer
# 20 = 夏日泼水节（泳池） / Water Splash Summer (pool)
# 21 = 夏日泼水节（泳池） + 圣诞节 / Water Splash Summer (pool) + Christmas
# 22 = 夏日泼水节（泳池） + 万圣节 / Water Splash Summer (pool) + Halloween
# 23 = 夏日泼水节（泳池） + 圣诞节 + 万圣节 / Water Splash Summer (pool) + Christmas + Halloween
# 24 = 夏日泼水节（泳池） + 情人节 / Water Splash Summer (pool) + Valentine
# 25 = 夏日泼水节（泳池） + 圣诞节 + 情人节 / Water Splash Summer (pool) + Christmas + Valentine
# 26 = 夏日泼水节（泳池） + 万圣节 + 情人节 / Water Splash Summer (pool) + Halloween + Valentine
# 27 = 夏日泼水节（泳池） + 万圣节 + 情人节 + 圣诞节 / Water Splash Summer (pool) + Halloween + Valentine + Christmas
# 28 = 夏日泼水节（泳池） + 夏日泼水节 / Water Splash Summer (pool) + Water Splash Summer
# 29 = 夏日泼水节（泳池） + 夏日泼水节 + 圣诞节 / Water Splash Summer (pool) + Water Splash Summer + Christmas
# 30 = 夏日泼水节（泳池） + 春节 / Water Splash Summer (pool) + Chinese New Year
# 31 = 夏日泼水节（泳池） + 春节 + 圣诞节 / Water Splash Summer (pool) + Chinese New Year + Christmas
# 32 = 夏日泼水节（泳池） + 春节 + 万圣节 / Water Splash Summer (pool) + Chinese New Year + Halloween
# 33 = 夏日泼水节（泳池） + 春节 + 万圣节 + 圣诞节 / Water Splash Summer (pool) + Chinese New Year + Halloween + Christmas
# 34 = 夏日泼水节（泳池） + 春节 + 情人节 / Water Splash Summer (pool) + Chinese New Year + Valentine
# 35 = 夏日泼水节（泳池） + 春节 + 圣诞节 + 情人节 / Water Splash Summer (pool) + Chinese New Year + Christmas + Valentine
# 36 = 夏日泼水节（泳池） + 春节 + 万圣节 + 情人节 / Water Splash Summer (pool) + Chinese New Year + Halloween + Valentine
# 37 = 夏日泼水节（泳池） + 春节 + 万圣节 + 情人节 + 圣诞节 / Water Splash Summer (pool) + Chinese New Year + Halloween + Valentine + Christmas
# 38 = 夏日泼水节（泳池） + 春节 + 夏日泼水节 / Water Splash Summer (pool) + Chinese New Year + Water Splash Summer
# 39 = 夏日泼水节（泳池） + 春节 + 夏日泼水节 + 圣诞节 / Water Splash Summer (pool) + Chinese New Year + Water Splash Summer + Christmas
# 默认值: 0 / Default: 0
gameserver.enable.decor = 37

# ==========================================
# 活动奖励 / Event Reward:
# ==========================================
# VIP 票据：
# VIP Tickets:
# 默认值: true / Default: true
gameserver.vip.tickets.enable = false

# 默认值: 30 / Default: 30
# 向每位玩家发送窗口：
# Send every player a Window:
# 使用 VIP 权益可以变得更强。\n 请在游戏商城查看 VIP 票据。
# You can become stronger with the VIP benefits.\n See the VIP Tickets in the in-game shop.
gameserver.vip.tickets.time = 10

# 觉醒活动 [日本活动]
# Event Awake [Event JAP]
# http://event2.ncsoft.jp/1.0/aion/1503awake/
# 觉醒活动 [日本活动]：
# Event Awake [Event JAP]:
# 默认值: false / Default: false
gameserver.event.awake.enable = false
# 默认值: 60 / Default: 60
gameserver.event.seed.transformation.time = 60

# ==========================================
# 激活服务器上所有“活动”
# Active all "Event on server"
# 默认值: false / Default: false
gameserver.event.service.enable = true

# “给予物品活动”
# "Give Item Event"
# 由 NPC Laylin 与 Ronya、Brios 与 Bothen 发放的物品
# Items which are given by NPCs Laylin and Ronya, Brios and Bothen
gameserver.events.give.juice = 160009017
gameserver.events.give.cake = 160010073

# ==========================================
# 欧比斯宝藏活动 / Treasure Abyss Event
# ==========================================
# 启用“欧比斯宝藏活动”
# Enable "Treasure Abyss Event"
# 默认值: true / Default: true
gameserver.event.abyss.treasure.enable = true
# 欧比斯宝藏活动开始时间
# Treasure Abyss event start time
gameserver.event.abyss.treasure.time = 0 0 22 ? * SUN
# 欧比斯宝藏活动奖励
# Treasure Abyss event rewards
gameserver.event.abyss.rewards = 187050043,187050041,187060099,187060225,187060264,1109011110,110901089,110901256,110900848,110901542,110901400,188055337,1880553336,1880570038,125045826,125045657,125045695,125045689,125045609,125045983,125045761,125046042,125050075

# ==========================================
# 波比猪活动 / Pig Poppy Event
# ==========================================
# 启用“波比猪活动”
# Enable "Pig Poppy Event"
# 默认值: true / Default: true
gameserver.event.pig.poppy.enable = true
# 波比猪活动开始时间
# Pig Poppy event start time
gameserver.event.pig.poppy = 0 0 22 ? * SAT
# 波比猪奖励数量
# Pig Poppy reward count
gameserver.event.pig.poppy.reward.count = 2
# 波比猪奖励
# Pig Poppy rewards
gameserver.pig.poppy.rewards = 125040073,125040072,125045189,187050035,187050037,110900707,110901277,110901424,164002144,164002009,110901273,125040045,110900809,110900809,110900542,110901406,110900846,110900847,110900848,125045076,110900104,110900105,125040044,110901029,110900482,110901280,110901526,110901290,110901609,110901262,110901025,110900441,110900443,125040128,125050013,160010208,190100015,190020133

# ==========================================
# 活动 4.3/4.7 / EVENT 4.3/4.7
# ==========================================
# “术古帝国陵墓 4.3”
# "Shugo Imperial Tomb 4.3"
# ==========================================
# 启用“术古帝国陵墓 4.3”
# Enable "Shugo Imperial Tomb 4.3"
# 默认值: true / Default: true
gameserver.shugo.imperial.tomb.enable = true
# “术古帝国陵墓 4.3”结束时间
# "Shugo Imperial Tomb 4.3" end time
# 默认值: 10 分钟 / Default: 10 min
gameserver.shugo.imperial.tomb.timer.from.start.to.end = 30
# “术古帝国陵墓 4.3”开始时间
# "Shugo Imperial Tomb 4.3" Start Times
# Cron 表达式，多个 cron 用 "|" 分隔
# Cron Expression, split by "|" for multiple crons
# 默认值: 0 0 0,18,21,23,2 ? * * / Default: 0 0 0,18,21,23,2 ? * *
gameserver.shugo.imperial.tomb.time.to.start = 0 0 0,18,21,23,2 ? * *

# ==========================================
# 疯狂守护者 / Crazy Daeva
# ==========================================
# 启用疯狂守护者
# Enable Crazy Daeva
# 默认值: false / Default: false
gameserver.crazy.daeva.enable = true
# 系统选择战斗者的最低随机值
# Lowest random value that system can be choose fighter
# 默认值: 10 / Default: 10
gameserver.crazy.daeva.lowest.rnd = 10
# 疯狂守护者开始时间
# Crazy Daeva Start Times
# Cron 表达式，多个 cron 用 "|" 分隔
# Cron Expression, split by "|" for multiple crons
# 默认值: 0 0 0,12,20,23,2,5,8 ? * * / Default: 0 0 0,12,20,23,2,5,8 ? * *
gameserver.crazy.daeva.time.to.start = 0 0 0,12,20,23,2,5,8 ? * *
# 停止活动的时间（分钟）
# Time in minutes to stop event
# 默认值: 30（30 分钟） / Default: 30 (30 minutes)
gameserver.crazy.daeva.endtime = 30

# ==========================================
# 升级街机 4.7 / Upgrade Arcade 4.7
# ==========================================
# 显示街机图标
# Show Arcade Icon
# 默认值: false / Default: false
gameserver.event.arcade.enable = true
# 街机概率
# Arcade Chance
# 默认值: 70 / Default: 70
gameserver.upgrade.arcade.chance = 70

# ==========================================
# 术古扫荡 / Shugo Sweep:
# ==========================================
# 术古扫荡棋盘 ID
# Shugo Sweep Board ID
# 棋盘 ID: 1 - 30
# Board ID: 1 - 30
# 默认值: 1 / Default: 1
gameserver.event.shugoSweep.board = 1

# 术古扫荡免费骰子
# Shugo Sweep Free Dice
# 默认值: 5 / Default: 5
gameserver.event.shugoSweep.freeDice = 5

# ==========================================
# YouTube 视频 / Youtube Video:
# ==========================================
# 默认值: https://www.youtube.com/embed/IOfgOpdybcM? / Default: https://www.youtube.com/embed/IOfgOpdybcM?
gameserver.event.youtube_video = https://www.youtube.com/embed/IOfgOpdybcM?
