# ==========================================
# PvP 模组配置:
# PvP Mod Config's:
# ==========================================
# 启用战场 PvP
# Enable BG PvP
# 默认值: false / Default: false
gameserver.pvp.mod.bg.enabled = false
