# ----------------------------
# 老兵奖励配置:
# Veteran Reward Config's:
# ----------------------------

# 启用/禁用老兵奖励系统
# Enable/Disable the Veteran Reward System
# 默认值: true / Default: true
gameserver.veteranreward.enabled = true
#
# 默认值: true / Default: true
gameserver.veteranreward.log_error = true
#
# 默认值: true / Default: true
gameserver.veteranreward.log_info = true
