package com.aionemu.gameserver.skillengine.effect;

/**
 * 技能效果类型枚举：与具体 {@link EffectTemplate} 实现一一对应。
 * Skill effect type enum: one-to-one with concrete {@link EffectTemplate} implementations.
 */
public enum EffectType {

	ABSOLUTEAPPOINTHEALINSTANT, ABSOLUTEEXPPOINTHEALINSTANT, ABSOLUTESLOW, ABSOLUTESNARE, ABSOLUTESTATTOPCBUFF,
	ABSOLUTESTATTOPCDEBUFF, ACTIVATEENSLAVE, ALWAYSBLOCK, ALWAYSDODGE, ALWAYSHIT, ALWAYSNORESIST, ALWAYSPARRY, ALWAYSRESIST,
	APBOOST, ARMORMASTERY,
	AURA, BACKDASH, BIND, BLEED, BLIND, BOOSTDROPRATE, BOOSTHATE, BOOSTHEAL, BOOSTSKILLCASTINGTIME, BOOSTSKILLCOST,
		BOOSTSPELLATTACK, BUFFBIND, BUFFSILENCE, BUFFSLEEP, BUFFSTUN, CANNON, CARVESIGNET, CASEHEAL, CASESKILL, CASESTATUP, CHANGEHATEONATTACKED,
	CLOSEAERIAL, CONDSKILLLAUNCHER, CONFUSE, CONVERTHEAL, CURSE, DASH, DEATHPENALTY, DEATHPENALTYREDUCE, DEATHBLOW, DEBOOSTHEAL, DEFORM,
	DELAYEDFPATKINSTANT, DELAYEDSKILL, DELAYEDSPELLATTACKINSTANT, DISEASE, DISPEL, DISPELBUFF, DISPELBUFFCOUNTERATK,
	DISPELDEBUFF, DISPELDEBUFFMENTAL, DISPELDEBUFFPHYSICAL, DISPELNPCBUFF, DISPELNPCDEBUFF, DPHEAL, DPHEALINSTANT,
	DPTRANSFER, DRBOOST, DOUBLEBOOST, DUMMY, ESCAPE, EVADE, EXTENDAURARANGE, FALL, FEAR, FLYOFF, FPATTACK,
	FPATTACKINSTANT, FPHEAL, FPHEALINSTANT, HEAL, HEALCASTORONATTACKED, HEALCASTORONTARGETDEAD, HEALINSTANT, HIDE,
	HIPASS, HOSTILEUP, INTERVALSKILL, INVULNERABLEWING, MAGICCOUNTERATK, MOVEBEHIND, MPATTACK, MPATTACKINSTANT, MPHEAL,
	MPHEALINSTANT, MPSHIELD, NODEATHPENALTY, NOFLY, NOREDUCESPELLATKINSTANT, NORESURRECTPENALTY, ONETIMEBOOSTHEAL,
	ONETIMEBOOSTSKILLATTACK, ONETIMEBOOSTSKILLCRITICAL, OPENAERIAL, PARALYZE, PETORDERUNSUMMON, PETORDERUSEULTRASKILL, PETRIFICATION,
	POISON, POLYMORPH, PROCATKINSTANT, PROCDPHEALINSTANT, PROCFPHEALINSTANT, PROCHEALINSTANT, PROCMPHEALINSTANT,
	PROCVPHEALINSTANT, PROTECT, PROVOKER, PULLED, RANDOMMOVELOC, REBIRTH, RECALLINSTANT, REFLECTOR, RESURRECT,
	RESURRECTBASE, RESURRECTPOSITIONAL, RETURN, RETURNCOOLREDUCE, RETURNPOINT, RIDEROBOT, ROOT, SANCTUARY, SEARCH, SHAPECHANGE, SHIELD,
	SHIELDMASTERY, SIGNET, SIGNETBURST, SILENCE, SIMPLEROOT, SKILLATKDRAININSTANT, SKILLATTACKINSTANT,
	SKILLCOOLTIMERESET, SKILLLAUNCHER, SKILLXPBOOST, SLEEP, SLOW, SNARE, SPELLATTACK, SPELLATKDRAIN, SPRINTFPREDUCE,
	SPELLATKDRAININSTANT, SPELLATTACKINSTANT, SPIN, STAGGER, STATBOOST, STATDOWN, STATUP, STUMBLE, STUN,
	SUBTYPEBOOSTRESIST, SUBTYPEEXTENDDURATION, SUMMON, SUMMONBINDINGGROUPGATE, SUMMONFUNCTIONALNPC, SUMMONGROUPGATE,
	SUMMONHOMING, SUMMONHOUSEGATE, SUMMONSERVANT, SUMMONSKILLAREA, SUMMONTOTEM, SUMMONTRAP, SUMMONKISK, SWITCHHOSTILE,
	SWITCHHPMP, TARGETCHANGE, TARGETTELEPORT, WEAPONSTATBOOST, WEAPONSTATUP, WEAPONDUAL, WEAPONMASTERY, XPBOOST, ODELLARECOVERINCREASE,
	XPHEALINSTANT, TEMPERINGPROTECTION;
}
