#!/usr/bin/env python3
"""Generate the production quest dialog page contract from the tracked client mapping CSVs.

The contract only keeps active/exact pages that have at least one client-visible action. The
compiler uses it to enforce the MOVIE_CONTINUATION_RESPONSE invariant at catalog compile time.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
from pathlib import Path


DEFAULT_PAGES = Path("docs/quest/client-dialog-mapping/quest-dialog-pages.csv")
DEFAULT_ACTIONS = Path("docs/quest/client-dialog-mapping/quest-dialog-action-details.csv")
DEFAULT_OUTPUT = Path("src/main/resources/aion/definitions/quest_dialog/client_dialog_contract.tsv")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pages", type=Path, default=DEFAULT_PAGES)
    parser.add_argument("--actions", type=Path, default=DEFAULT_ACTIONS)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true",
                        help="fail when the checked-in contract does not match the CSVs")
    return parser.parse_args()


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def sanitize(value: str) -> str:
    return value.replace("\t", " ").replace("\r", " ").replace("\n", " ").strip()


def generate(pages_path: Path, actions_path: Path) -> str:
    pages: dict[tuple[int, int], str] = {}
    with pages_path.open(encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            if row["source_variant"] != "active" or row["page_mapping"] != "exact":
                continue
            try:
                action_count = int(row["action_count"])
                quest_id = int(row["quest_id"])
                page_id = int(row["page_id"])
            except ValueError:
                continue
            if action_count <= 0:
                continue
            pages[(quest_id, page_id)] = sanitize(row["html_page_name"])

    lines = [
        "# generated by .agents/summary/quest/generate_quest_dialog_contract.py",
        f"# source_pages_sha256={sha256(pages_path)}",
        f"# source_actions_sha256={sha256(actions_path)}",
        "# filters=source_variant:active,page_mapping:exact,action_count>0",
        "# quest_id\tpage_id\tpage_name",
    ]
    lines.extend(f"{quest_id}\t{page_id}\t{pages[(quest_id, page_id)]}" for quest_id, page_id in sorted(pages))
    return "\n".join(lines) + "\n"


def main() -> None:
    args = parse_args()
    rendered = generate(args.pages, args.actions)
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.is_file() else None
        if current != rendered:
            raise SystemExit(f"quest dialog contract is stale: {args.output}")
        print(f"QUEST_DIALOG_CONTRACT_OK FILE={args.output}")
        return
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"QUEST_DIALOG_CONTRACT_WRITTEN={args.output}")


if __name__ == "__main__":
    main()
