package com.aionemu.gameserver.model;

/**
 * 任务 ID 枚举。
 * Task Id enumeration.
 */

public enum TaskId {
	/** 腐朽 / Decay. */
	DECAY, RESPAWN, PRISON, PROTECTION_ACTIVE, DROWN, DESPAWN, QUEST_TIMER, QUEST_FOLLOW, PLAYER_UPDATE,
	/** 背包更新 / Inventory Update*/
	INVENTORY_UPDATE, GAG, ITEM_USE, ACTION_ITEM_NPC, HOUSE_OBJECT_USE, EXPRESS_MAIL_USE, SKILL_USE, GATHERABLE,
	/** 宠物更新 / Pet Update*/
	PET_UPDATE, SUMMON_FOLLOW, ZONE_MATERIAL_ACTION, TERRAIN_MATERIAL_ACTION, HOTSPOT_TELEPORT, FFA, PK, THIEVES, MINION_UPDATE, MINION_TELEPORT_CHECK;
}
