#!/usr/bin/env python3
"""Render derived memory-bank indexes from Pattern metadata blocks.

Two derived artifacts are produced and checked together:

- ``symptom-index.md``: human-readable symptom/keyword routing table.
- ``index.jsonl``: machine-readable per-Pattern index for agent retrieval.
- ``.agents/summary/index.jsonl``: one record per evidence document referenced by a Pattern.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

from memory_bank import ENTRY_FIELDS, iter_pattern_entries, render_index_jsonl


SYMPTOM_INDEX_FILE = "symptom-index.md"
PATTERN_INDEX_FILE = "index.jsonl"
SUMMARY_INDEX_RELATIVE = ".agents/summary/index.jsonl"
SUMMARY_DOC_REF = re.compile(r"\.agents/summary/[A-Za-z0-9._/-]+\.md")
H1_TITLE = re.compile(r"^#\s+(?P<title>.+)$", re.MULTILINE)
DATE_PREFIX = re.compile(r"^(?P<date>\d{4}-\d{2}-\d{2})-")
SUMMARY_KIND_PATTERNS = (
    ("acceptance", re.compile(r"accept", re.IGNORECASE)),
    ("audit", re.compile(r"audit", re.IGNORECASE)),
    ("evidence", re.compile(r"evidence", re.IGNORECASE)),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Sync derived memory-bank indexes.")
    parser.add_argument("--check", action="store_true", help="fail when a derived file is stale")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    return parser.parse_args()


def markdown_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def render_symptom_index(entries) -> str:
    lines = [
        "<!-- Generated by sync_memory_bank.py. Edit patterns/*.md metadata, then run this script. -->",
        "# Symptom Index (症状与关键词索引)",
        "",
        "按玩家现象、日志关键词或代码信号先定位 Pattern ID，再展开对应模式卡。索引由 Pattern 元数据生成，只负责缩小搜索范围，不能替代模式卡中的证据和边界判断。",
        "",
        "| 症状/关键词 | Pattern ID | 第一检查点 |",
        "|---|---|---|",
    ]
    for entry in sorted(entries, key=lambda item: item.pattern_id):
        metadata = entry.metadata
        lines.append(
            f"| {markdown_cell(metadata.get('symptom', ''))} | `{entry.pattern_id}` | "
            f"{markdown_cell(metadata.get('first_check', ''))} |"
        )
    return "\n".join(lines) + "\n"


def summary_kind(name: str) -> str:
    """Classify one summary document by its filename."""
    if name.lower() == "readme.md":
        return "topic-readme"
    for kind, pattern in SUMMARY_KIND_PATTERNS:
        if pattern.search(name):
            return kind
    return "report" if DATE_PREFIX.match(name) else "other"


def render_summary_index(entries, root: Path) -> str:
    """Render one record per evidence document that a Pattern cites.

    Only referenced documents are indexed: the index exists to expand a Pattern into its
    evidence, so it stays in lockstep with the Pattern cards and never needs a separate scan of
    every task directory.
    """
    owners: dict[str, set[str]] = {}
    for entry in entries:
        for ref in SUMMARY_DOC_REF.findall(entry.metadata.get("evidence", "")):
            owners.setdefault(ref, set()).add(entry.pattern_id)

    records: list[dict[str, object]] = []
    missing: list[str] = []
    for ref, pattern_ids in sorted(owners.items()):
        path = root / ref
        if not path.is_file():
            missing.append(ref)
            continue
        text = path.read_text(encoding="utf-8")
        title = H1_TITLE.search(text)
        records.append(
            {
                "record": "summary",
                "path": ref,
                "topic": path.parent.name,
                "kind": summary_kind(path.name),
                "date": (DATE_PREFIX.match(path.name).group("date") if DATE_PREFIX.match(path.name) else ""),
                "title": title.group("title").strip() if title else "",
                "lines": text.count("\n") + 1,
                "bytes": len(text.encode("utf-8")),
                "sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(),
                "referenced_by": sorted(pattern_ids),
            }
        )

    meta = {
        "record": "meta",
        "schema": 1,
        "generator": "sync_memory_bank.py",
        "entry_count": len(records),
        "missing": sorted(missing),
        "fields": ["path", "topic", "kind", "date", "title", "lines", "bytes", "sha256", "referenced_by"],
    }
    lines = [
        json.dumps(record, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        for record in [meta, *records]
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    args = parse_args()
    root = args.root.resolve()
    bank = root / ".agents/memory-bank"
    entries = list(iter_pattern_entries(bank / "patterns"))
    errors: list[str] = []
    seen: set[str] = set()
    for entry in entries:
        if entry.pattern_id in seen:
            errors.append(f"duplicate Pattern ID: {entry.pattern_id}")
        seen.add(entry.pattern_id)
        for field in ENTRY_FIELDS:
            if not entry.metadata.get(field):
                errors.append(f"{entry.card}:{entry.line}: missing {field}")
    if errors:
        print("MEMORY_BANK_SYNC_FAILED")
        for error in errors:
            print(f"- {error}")
        raise SystemExit(1)

    derived = (
        (bank / SYMPTOM_INDEX_FILE, render_symptom_index(entries)),
        (bank / PATTERN_INDEX_FILE, render_index_jsonl(entries, root)),
        (root / SUMMARY_INDEX_RELATIVE, render_summary_index(entries, root)),
    )
    stale: list[Path] = []
    for target, rendered in derived:
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current == rendered:
            continue
        if args.check:
            stale.append(target)
            continue
        target.write_text(rendered, encoding="utf-8")
        print(f"MEMORY_BANK_SYNC_WROTE {target}")

    if stale:
        for target in stale:
            print(f"MEMORY_BANK_INDEX_STALE {target}")
        raise SystemExit(1)
    print(f"MEMORY_BANK_SYNC_OK ENTRIES={len(entries)}")


if __name__ == "__main__":
    main()
