#!/usr/bin/env python3
"""Render derived memory-bank indexes from Pattern metadata blocks.

Two derived artifacts are produced and checked together:

- ``symptom-index.md``: human-readable symptom/keyword routing table.
- ``index.jsonl``: machine-readable per-Pattern index for agent retrieval.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from memory_bank import ENTRY_FIELDS, iter_pattern_entries, render_index_jsonl


SYMPTOM_INDEX_FILE = "symptom-index.md"
PATTERN_INDEX_FILE = "index.jsonl"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Sync derived memory-bank indexes.")
    parser.add_argument("--check", action="store_true", help="fail when a derived file is stale")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    return parser.parse_args()


def markdown_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def render_symptom_index(entries) -> str:
    lines = [
        "<!-- Generated by sync_memory_bank.py. Edit patterns/*.md metadata, then run this script. -->",
        "# Symptom Index (症状与关键词索引)",
        "",
        "按玩家现象、日志关键词或代码信号先定位 Pattern ID，再展开对应模式卡。索引由 Pattern 元数据生成，只负责缩小搜索范围，不能替代模式卡中的证据和边界判断。",
        "",
        "| 症状/关键词 | Pattern ID | 第一检查点 |",
        "|---|---|---|",
    ]
    for entry in sorted(entries, key=lambda item: item.pattern_id):
        metadata = entry.metadata
        lines.append(
            f"| {markdown_cell(metadata.get('symptom', ''))} | `{entry.pattern_id}` | "
            f"{markdown_cell(metadata.get('first_check', ''))} |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    args = parse_args()
    root = args.root.resolve()
    bank = root / ".agents/memory-bank"
    entries = list(iter_pattern_entries(bank / "patterns"))
    errors: list[str] = []
    seen: set[str] = set()
    for entry in entries:
        if entry.pattern_id in seen:
            errors.append(f"duplicate Pattern ID: {entry.pattern_id}")
        seen.add(entry.pattern_id)
        for field in ENTRY_FIELDS:
            if not entry.metadata.get(field):
                errors.append(f"{entry.card}:{entry.line}: missing {field}")
    if errors:
        print("MEMORY_BANK_SYNC_FAILED")
        for error in errors:
            print(f"- {error}")
        raise SystemExit(1)

    derived = (
        (bank / SYMPTOM_INDEX_FILE, render_symptom_index(entries)),
        (bank / PATTERN_INDEX_FILE, render_index_jsonl(entries, root)),
    )
    stale: list[Path] = []
    for target, rendered in derived:
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current == rendered:
            continue
        if args.check:
            stale.append(target)
            continue
        target.write_text(rendered, encoding="utf-8")
        print(f"MEMORY_BANK_SYNC_WROTE {target}")

    if stale:
        for target in stale:
            print(f"MEMORY_BANK_INDEX_STALE {target}")
        raise SystemExit(1)
    print(f"MEMORY_BANK_SYNC_OK ENTRIES={len(entries)}")


if __name__ == "__main__":
    main()
