package com.aionemu.tools.questgen;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/**
 * P4d 构建期生成器：把 monster 系客户端投影表从手工快照改为从入仓源重建。
 * <p>
 * 输入：{@code src/main/resources/aion/definitions/quest_monster/quest_monster.csv}（入仓的客户端
 * {@code Quest_unpacked/quest_monster.csv}，会持续修订，不钉 sha）与 {@code npcs/npc_template_*.xml}。
 * <p>
 * 输出（{@code <outputRoot>/aion/data/static_data/quest_retail/}）：
 * <ul>
 *   <li>{@code quest_client_hunt_progress_rows.tsv}</li>
 *   <li>{@code quest_client_hunt_stages.tsv}</li>
 *   <li>{@code quest_client_kill_targets_stages.tsv}</li>
 * </ul>
 * {@code quest_client_kill_targets.tsv} 不在本生成器范围：它的生成源是任务 XML，而那些 XML
 * 已随真端迁移退役（45/45 缺失），该表由 P4c 单源冻结保留为唯一权威。
 * 生成逻辑逐行移植自 .agents/summary/scriptdll-quest-driver/ 与
 * .agents/summary/quest-15546-kill-progress/ 的 Python 分析脚本（那些脚本只登记停写，不再运行）。
 * <p>
 * Build-time generator for the monster-family client projection tables (P4d): faithfully ported
 * from the retired Python analysis scripts so regenerated bytes stay identical.
 * <p>
 * Usage: {@code QuestMonsterTableGenerator <repoRoot> <outputRoot>}
 */
public final class QuestMonsterTableGenerator {

	private static final Pattern NPC_TAG = Pattern.compile("<npc_template\\b[^>]*>");
	private static final Pattern NPC_ID = Pattern.compile("npc_id=\"(\\d+)\"");
	private static final Pattern NAME_DESC = Pattern.compile("name_desc=\"([^\"]*)\"");
	private static final Pattern HUNT_GATE = Pattern.compile(
		"^Progress\\(SECTION_0==(\\d+)(?:; SECTION_([1-9]\\d*)<(\\d+))?\\)$");
	private static final Pattern SECTION_COUNT = Pattern.compile("SECTION_(\\d+)<(\\d+)");

	private static final List<Integer> HUNT_STAGE_FAMILY =
		List.of(13918, 16991, 18911, 18912, 23918, 26991, 28911, 28912, 30600, 30610);
	private static final List<Integer> KILL_TARGET_STAGE_QUESTS = List.of(15546, 25546);
	private final Path repo;
	private final Path outputRoot;

	private QuestMonsterTableGenerator(Path repo, Path outputRoot) {
		this.repo = repo;
		this.outputRoot = outputRoot;
	}

	public static void main(String[] args) throws Exception {
		if (args.length != 2) {
			System.err.println("usage: QuestMonsterTableGenerator <repoRoot> <outputRoot>");
			System.exit(2);
		}
		new QuestMonsterTableGenerator(Path.of(args[0]).toAbsolutePath().normalize(),
			Path.of(args[1]).toAbsolutePath().normalize()).run();
	}

	private void run() throws IOException {
		Path aion = repo.resolve("src/main/resources/aion");
		Path staticData = aion.resolve("data/static_data");
		Path csv = aion.resolve("definitions/quest_monster/quest_monster.csv");
		if (!Files.isRegularFile(csv)) {
			throw new IOException("missing generation source: " + csv);
		}
		List<List<String>> rows = readCsv(csv);
		Path outDir = outputRoot.resolve("aion/data/static_data/quest_retail");
		Files.createDirectories(outDir);

		generateHuntProgressRows(rows, outDir.resolve("quest_client_hunt_progress_rows.tsv"));
		generateHuntStages(rows, staticData, outDir.resolve("quest_client_hunt_stages.tsv"));
		generateKillTargetStages(rows, staticData, outDir.resolve("quest_client_kill_targets_stages.tsv"));
		System.out.println("QuestMonsterTableGenerator: wrote 3 tables to " + outDir);
	}

	/** ① simpleQuest 进度行（源：quest_monster.csv）。 / SimpleQuest progress rows from the client CSV. */
	private void generateHuntProgressRows(List<List<String>> rows, Path outFile) throws IOException {
		Map<Integer, List<Progress>> byQuest = new TreeMap<>();
		for (List<String> r : rows) {
			if (r.isEmpty() || !isDigits(r.get(0).strip()) || r.size() < 7 || !"simpleQuest".equals(r.get(3).strip())) {
				continue;
			}
			Matcher m = HUNT_GATE.matcher(r.get(1).strip());
			if (!m.matches() || m.group(2) == null) {
				continue;
			}
			List<String> monsters = new ArrayList<>();
			for (int i = 6; i < r.size(); i++) {
				String value = r.get(i).strip();
				if (!value.isEmpty()) {
					monsters.add(value);
				}
			}
			if (monsters.isEmpty()) {
				continue;
			}
			byQuest.computeIfAbsent(Integer.parseInt(r.get(0).strip()), key -> new ArrayList<>())
				.add(new Progress(Integer.parseInt(m.group(1)), Integer.parseInt(m.group(2)),
					Integer.parseInt(m.group(3)), monsters));
		}
		Comparator<List<String>> listOrder = QuestMonsterTableGenerator::compareStringLists;
		Comparator<Progress> order = Comparator.comparingInt(Progress::ladderRow)
			.thenComparingInt(Progress::section).thenComparingInt(Progress::count)
			.thenComparing(Progress::monsters, listOrder);

		List<String> out = new ArrayList<>();
		out.add("# 客户端 hunt 进度行登记表（混合链 SECTION 校准；source: Quest_unpacked/quest_monster.csv simpleQuest 行）");
		out.add("# Client hunt progress rows (mixed-chain SECTION calibration; simpleQuest rows of quest_monster.csv).");
		out.add("# quest_id\tladder_row\tsection\tcount\tmonsters(';' joined)");
		for (Map.Entry<Integer, List<Progress>> entry : byQuest.entrySet()) {
			List<Progress> list = new ArrayList<>(entry.getValue());
			list.sort(order);
			for (Progress row : list) {
				out.add(entry.getKey() + "\t" + row.ladderRow() + "\t" + row.section() + "\t" + row.count()
					+ "\t" + String.join(";", row.monsters()));
			}
		}
		writeLines(outFile, out);
	}

	/** ② SimpleSerialHunt 串行阶段（源：quest_monster.csv 的 10 个任务族）。 / Serial-hunt stages. */
	private void generateHuntStages(List<List<String>> rows, Path staticData, Path outFile) throws IOException {
		Map<String, Set<Integer>> descToIds = npcNameIndex(staticData, true);
		Map<Integer, List<List<String>>> byQuest = new LinkedHashMap<>();
		for (List<String> row : rows) {
			if (row.isEmpty() || !isDigits(row.get(0).strip())) {
				continue;
			}
			int questId = Integer.parseInt(row.get(0).strip());
			if (HUNT_STAGE_FAMILY.contains(questId)) {
				byQuest.computeIfAbsent(questId, key -> new ArrayList<>()).add(row);
			}
		}
		List<String> out = new ArrayList<>();
		out.add("# 客户端串行阶段契约登记（SimpleSerialHunt；由 p3_client_hunt_stages.py 生成）");
		out.add("# quest_id\tstage\tcount\tnpc_ids\tnames");
		List<String> unresolved = new ArrayList<>();
		for (int questId : HUNT_STAGE_FAMILY) {
			int stageIndex = 1;
			for (List<String> row : byQuest.getOrDefault(questId, List.of())) {
				String gate = row.size() > 1 ? row.get(1) : "";
				Matcher m = Pattern.compile("SECTION_" + (stageIndex - 1) + "<(\\d+)").matcher(gate);
				int count = m.find() ? Integer.parseInt(m.group(1)) : 1;
				List<String> ids = new ArrayList<>();
				List<String> names = new ArrayList<>();
				for (int i = 6; i < row.size(); i++) {
					String name = row.get(i);
					if (name.isEmpty()) {
						continue;
					}
					Set<Integer> hits = descToIds.getOrDefault(name.toLowerCase(Locale.ROOT), Set.of());
					if (hits.size() == 1) {
						ids.add(String.valueOf(hits.iterator().next()));
						names.add(name);
					} else {
						unresolved.add(questId + "/" + stageIndex + "/" + name + ":" + hits.size());
					}
				}
				if (!ids.isEmpty()) {
					out.add(questId + "\t" + stageIndex + "\t" + count + "\t" + String.join(",", ids)
						+ "\t" + String.join(",", names));
				}
				stageIndex++;
			}
		}
		writeLines(outFile, out);
		System.out.println("hunt_stages: rows=" + (out.size() - 2) + " unresolved=" + unresolved.size()
			+ (unresolved.isEmpty() ? "" : " " + unresolved.subList(0, Math.min(10, unresolved.size()))));
	}

	/** ③ 多段 hunt 的逐段击杀目标（源：quest_monster.csv 的 15546/25546）。 / Per-stage kill targets. */
	private void generateKillTargetStages(List<List<String>> rows, Path staticData, Path outFile) throws IOException {
		Map<String, List<Integer>> nameToIds = npcNameIndexList(staticData);
		List<String> out = new ArrayList<>();
		out.add("# 逐段击杀目标登记表（多段 DD hunt 行的变体轴裁定；段号 = DD 计数槽 1..N）");
		out.add("# source: Quest_unpacked/quest_monster.csv 每 SECTION 行的名字变体经 npc_template name_desc 解析");
		out.add("# 生成脚本: .agents/summary/scriptdll-quest-driver/generate_stage_kill_targets.py");
		out.add("# quest_id\tstage\ttargets");
		List<String> problems = new ArrayList<>();
		for (int questId : KILL_TARGET_STAGE_QUESTS) {
			Map<Integer, Set<Integer>> perStage = new TreeMap<>();
			for (List<String> row : rows) {
				if (row.isEmpty() || !row.get(0).strip().equals(String.valueOf(questId))) {
					continue;
				}
				String gate = row.size() > 1 ? row.get(1) : "";
				Matcher m = SECTION_COUNT.matcher(gate);
				if (!m.find()) {
					problems.add(questId + " no counter section: " + gate);
					continue;
				}
				int slot = Integer.parseInt(m.group(1));
				for (int i = 6; i < row.size(); i++) {
					for (String tokenRaw : row.get(i).split("\\s+")) {
						String token = tokenRaw.strip().toLowerCase(Locale.ROOT);
						if (token.isEmpty()) {
							continue;
						}
						List<Integer> ids = nameToIds.get(token);
						if (ids == null || ids.isEmpty()) {
							problems.add(questId + " unresolved: " + token);
							continue;
						}
						perStage.computeIfAbsent(slot, key -> new TreeSet<>()).addAll(ids);
					}
				}
			}
			for (Map.Entry<Integer, Set<Integer>> entry : perStage.entrySet()) {
				out.add(questId + "\t" + entry.getKey() + "\t"
					+ entry.getValue().stream().map(String::valueOf).collect(Collectors.joining(" ")));
			}
		}
		writeLines(outFile, out);
		System.out.println("kill_targets_stages: rows=" + (out.size() - 4) + " problems=" + problems.size()
			+ (problems.isEmpty() ? "" : " " + problems.subList(0, Math.min(10, problems.size()))));
	}

	// ---------------------------------------------------------------------------------------------
	// 共享工具 / Shared helpers
	// ---------------------------------------------------------------------------------------------

	private static List<List<String>> readCsv(Path path) throws IOException {
		List<String> lines = Files.readAllLines(path, StandardCharsets.UTF_8);
		List<List<String>> rows = new ArrayList<>(lines.size());
		for (int i = 0; i < lines.size(); i++) {
			String line = lines.get(i);
			if (i == 0 && line.startsWith("\uFEFF")) {
				line = line.substring(1);
			}
			if (line.isEmpty()) {
				continue;
			}
			rows.add(Arrays.asList(line.split(",", -1)));
		}
		return rows;
	}

	/** name_desc（小写）→ npc id 集。 / Lower-case name_desc to npc ids. */
	private static Map<String, Set<Integer>> npcNameIndex(Path staticData, boolean templatesOnly) throws IOException {
		Map<String, Set<Integer>> index = new LinkedHashMap<>();
		for (Path file : listFiles(staticData.resolve("npcs"), ".xml")) {
			if (templatesOnly && !file.getFileName().toString().startsWith("npc_template_")) {
				continue;
			}
			collectNpcNames(Files.readString(file, StandardCharsets.UTF_8), index);
		}
		return index;
	}

	/** name_desc（小写）→ npc id 列表（保留重复，供 kill-target 生成器逐段合并）。 / Name to id list. */
	private static Map<String, List<Integer>> npcNameIndexList(Path staticData) throws IOException {
		Map<String, Set<Integer>> sets = npcNameIndex(staticData, false);
		Map<String, List<Integer>> lists = new LinkedHashMap<>();
		sets.forEach((name, ids) -> lists.put(name, new ArrayList<>(ids)));
		return lists;
	}

	private static void collectNpcNames(String text, Map<String, Set<Integer>> index) {
		Matcher tag = NPC_TAG.matcher(text);
		while (tag.find()) {
			String segment = tag.group();
			Matcher id = NPC_ID.matcher(segment);
			Matcher name = NAME_DESC.matcher(segment);
			if (id.find() && name.find()) {
				index.computeIfAbsent(name.group(1).toLowerCase(Locale.ROOT), key -> new LinkedHashSet<>())
					.add(Integer.parseInt(id.group(1)));
			}
		}
	}

	private static List<Path> listFiles(Path dir, String suffix) throws IOException {
		if (!Files.isDirectory(dir)) {
			throw new IOException("missing directory: " + dir);
		}
		List<Path> files = new ArrayList<>();
		try (DirectoryStream<Path> stream = Files.newDirectoryStream(dir, "*" + suffix)) {
			for (Path path : stream) {
				files.add(path);
			}
		}
		files.sort(Comparator.comparing(path -> path.getFileName().toString()));
		return files;
	}

	private static List<Path> listFilesRecursive(Path dir, String suffix) throws IOException {
		if (!Files.isDirectory(dir)) {
			throw new IOException("missing directory: " + dir);
		}
		try (var stream = Files.walk(dir)) {
			return stream.filter(Files::isRegularFile)
				.filter(path -> path.getFileName().toString().endsWith(suffix))
				.sorted(Comparator.comparing(Path::toString))
				.toList();
		}
	}

	private static void writeLines(Path file, List<String> lines) throws IOException {
		Files.write(file, (String.join("\n", lines) + "\n").getBytes(StandardCharsets.UTF_8));
	}

	private static boolean isDigits(String value) {
		if (value.isEmpty()) {
			return false;
		}
		for (int i = 0; i < value.length(); i++) {
			if (!Character.isDigit(value.charAt(i))) {
				return false;
			}
		}
		return true;
	}

	private static int compareStringLists(List<String> left, List<String> right) {
		int common = Math.min(left.size(), right.size());
		for (int i = 0; i < common; i++) {
			int result = left.get(i).compareTo(right.get(i));
			if (result != 0) {
				return result;
			}
		}
		return Integer.compare(left.size(), right.size());
	}

	private record Progress(int ladderRow, int section, int count, List<String> monsters) {
	}
}
