package com.aionemu.tools.questgen;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * P4e-1 构建期生成器：客户端 talk+collect 混合链页梯登记表（{@code quest_client_talk_collect_chain_pages.tsv}）。
 * <p>
 * 仓内源：{@code data_driven_quest.xml} 的步骤类别、{@code docs/quest/client-dialog-mapping/quest-dialog-pages.csv}
 * 与 {@code quest-dialog-action-details.csv} 的按钮图、{@code quest_client_handin_pages.tsv} 与
 * {@code quest_client_talk_chain_pages.tsv} 的归属排除集；非仓内/已退役输入（退役 talk_pages 的 7 个
 * 排除 id、客户端 HTML 的 11 条过场事实、2 个刻意 WITHHELD 行）由
 * {@code aion/definitions/quest_dialog/talk_collect_frozen_facts.csv} 冻结承载。
 * <p>
 * 逐行移植自 {@code .agents/summary/scriptdll-quest-driver/build_quest_client_talk_collect_chain_pages.py}
 * （该分析脚本只登记停写，不再运行）：eligible 规则、{@code select{i}} 按钮图 BFS 页梯、阶段类别与真端
 * stepCategories 逐位对齐、collect 段的 39/20002 检查与 ok/fail 结果页、梯尾页过场附加、exclude/withheld 过滤。
 * <p>
 * Build-time generator for the talk+collect mixed-chain page-ladder registry (P4e-1), ported line by
 * line from the retired Python analysis script so the regenerated bytes stay identical.
 * <p>
 * Usage: {@code QuestTalkCollectChainPagesGenerator <repoRoot> <outputRoot>}
 */
public final class QuestTalkCollectChainPagesGenerator {

	/** collect 段推进按钮（39 检查 / 20002 检查）。 / Collect-stage advance buttons. */
	private static final Set<Integer> COLLECT_ADVANCE_IDS = Set.of(39, 20002);
	/** talk 段推进按钮（SETPRO* / SET_SUCCEED / 1009）。 / Talk-stage advance buttons. */
	private static final Set<Integer> TALK_ADVANCE_IDS = Set.of(
		10000, 10001, 10002, 10003, 10004, 10005, 10006, 10007, 10008, 10009, 10010, 10011, 10255, 1009);
	/** collect 段结果页（check_user_item_ok / fail）。 / Collect-stage result pages. */
	private static final Set<String> RESULT_PAGES = Set.of("check_user_item_ok", "check_user_item_fail");
	/** 收尾按钮 FINISH_DIALOG(1008) 不收进 collect 段导航扇出。 / FINISH_DIALOG is not a nav. */
	private static final int FINISH_DIALOG_BUTTON = 1008;
	/** 生成物表头（与手工表逐字节一致，改表头等于改冻结面）。 / Output header, byte-stable. */
	private static final List<String> HEADER = List.of(
		"# 客户端 talk+collect 混合链登记（quest_id, entry_page, 阶段1, 阶段2 ...）",
		"# 每阶段列 = `talk:p1>p2>...:advance` 或 `collect:p:advance:ok页:fail页`；"
			+ "# talk 段梯 = select{i} 出发的按钮图导航链，collect 段 = 39/20002 检查 + 结果页；"
			+ "# 阶段类别序列与真端表 stepCategories 逐位一致（登记即证据对齐）",
		"# 来源：data_driven_quest.xml + quest-dialog-pages.csv + quest-dialog-action-details.csv",
		"# 生成：src/main/generator/java/com/aionemu/tools/questgen/QuestTalkCollectChainPagesGenerator.java"
			+ "（移植自 .agents/summary/scriptdll-quest-driver/build_quest_client_talk_collect_chain_pages.py，该脚本停写）");

	private static final Pattern QUEST_BLOCK =
		Pattern.compile("<quest_data_driven>(.*?)</quest_data_driven>", Pattern.DOTALL);
	private static final Pattern QUEST_ID = Pattern.compile("<id>(\\d+)</id>");
	private static final Pattern PROGRESS_CATEGORY =
		Pattern.compile("<category_progress_>(.*?)</category_progress_>");
	private static final Pattern ACQUIRE_CATEGORY =
		Pattern.compile("<category_acquire_>(.*?)</category_acquire_>");
	private static final Pattern STAGE_HEAD = Pattern.compile("select(\\d+)");

	private static final String FACTS_FILE = "src/main/resources/aion/definitions/quest_dialog/talk_collect_frozen_facts.csv";
	private static final String DD_XML = "src/main/resources/aion/data/static_data/quest_retail/data_driven_quest.xml";
	private static final String HANDIN_TABLE = ".agents/summary/quest-native-dispatch/retired-tsv/quest_client_handin_pages.tsv.retired-20260928";
	private static final String CHAIN_TABLE = ".agents/summary/quest-native-dispatch/retired-tsv/quest_client_talk_chain_pages.tsv.retired-20260928";
	private static final String PAGES_CSV = "docs/quest/client-dialog-mapping/quest-dialog-pages.csv";
	private static final String ACTIONS_CSV = "docs/quest/client-dialog-mapping/quest-dialog-action-details.csv";
	private static final String OUTPUT_TABLE = "aion/data/static_data/quest_retail/quest_client_talk_collect_chain_pages.tsv";

	private final Path repo;
	private final Path outputRoot;

	private QuestTalkCollectChainPagesGenerator(Path repo, Path outputRoot) {
		this.repo = repo;
		this.outputRoot = outputRoot;
	}

	public static void main(String[] args) throws Exception {
		if (args.length != 2) {
			System.err.println("usage: QuestTalkCollectChainPagesGenerator <repoRoot> <outputRoot>");
			System.exit(2);
		}
		new QuestTalkCollectChainPagesGenerator(Path.of(args[0]).toAbsolutePath().normalize(),
			Path.of(args[1]).toAbsolutePath().normalize()).run();
	}

	private void run() throws IOException {
		Path facts = require(FACTS_FILE);
		Path ddXml = require(DD_XML);
		Path handin = require(HANDIN_TABLE);
		Path chain = require(CHAIN_TABLE);
		Path pagesCsv = require(PAGES_CSV);
		Path actionsCsv = require(ACTIONS_CSV);

		Facts frozen = readFacts(facts);
		Map<Integer, DdQuest> dd = readDataDriven(ddXml);
		Map<Integer, Map<String, Integer>> pageIdByName = new LinkedHashMap<>();
		Map<Integer, Set<Integer>> pageIds = new HashMap<>();
		readPagesCsv(pagesCsv, pageIdByName, pageIds);
		Map<Integer, Map<Integer, List<Integer>>> buttons = readActionsCsv(actionsCsv);

		Set<Integer> claimed = new HashSet<>();
		claimed.addAll(readIdColumn(handin));
		claimed.addAll(readIdColumn(chain));
		claimed.addAll(frozen.exclusions());

		Map<String, Integer> skipped = new LinkedHashMap<>();
		for (String kind : List.of("claimed", "no_pages", "stage_mismatch", "multi_advance")) {
			skipped.put(kind, 0);
		}
		List<String> rows = new ArrayList<>();
		for (Map.Entry<Integer, DdQuest> entry : new TreeMap<>(dd).entrySet()) {
			int questId = entry.getKey();
			DdQuest quest = entry.getValue();
			if (claimed.contains(questId)) {
				bump(skipped, "claimed");
				continue;
			}
			Map<String, Integer> names = pageIdByName.get(questId);
			Set<Integer> ids = pageIds.getOrDefault(questId, Set.of());
			int entryPage = 0;
			// EnterWorld/EnterArea/None 接取行没有 select_none 接取页（任务由事件发放，简报在步骤 1 的
			// talk NPC）：entry_page=0。 / Event-granted rows carry no acquire page.
			if (names != null && names.containsKey("select_none")) {
				entryPage = names.get("select_none");
			} else if (!(names != null && List.of("enterworld", "enterarea", "none").contains(quest.acquireCategory()))) {
				bump(skipped, "no_pages");
				continue;
			}
			// 结果页仅 collect 行必需；talk/hunt(/EA) 行没有 39 检查页。
			// Result pages are required only for collect rows.
			if (names == null || (quest.categories().contains("collect") && !names.keySet().containsAll(RESULT_PAGES))) {
				bump(skipped, "no_pages");
				continue;
			}
			Map<Integer, List<Integer>> questButtons = buttons.getOrDefault(questId, Map.of());
			List<Stage> stages = new ArrayList<>();
			boolean aborted = false;
			// 段首页 = 任务实际存在的 select{i} 页（客户端可跳号）。 / Stage heads are the select{i}
			// pages that actually exist; the client may skip numbers.
			for (Map.Entry<Integer, Integer> head : stageHeads(names).entrySet()) {
				List<Integer> pageButtons = questButtons.getOrDefault(head.getValue(), List.of());
				List<Integer> collectAdvance = new ArrayList<>();
				for (int button : pageButtons) {
					if (COLLECT_ADVANCE_IDS.contains(button)) {
						collectAdvance.add(button);
					}
				}
				if (!collectAdvance.isEmpty()) {
					// collect 段不终止链：段梯 = 段首页 + 首页上的信息导航页（扇出，排除检查/推进/收尾按钮）。
					// A collect stage does not end the chain: head page plus its information navs.
					List<Integer> ordered = new ArrayList<>(List.of(head.getValue()));
					Set<Integer> seenNavs = new HashSet<>(ordered);
					for (int button : pageButtons) {
						if (COLLECT_ADVANCE_IDS.contains(button) || TALK_ADVANCE_IDS.contains(button)
							|| !ids.contains(button) || button == FINISH_DIALOG_BUTTON) {
							continue;
						}
						if (seenNavs.add(button)) {
							ordered.add(button);
						}
					}
					stages.add(new Stage("collect", ordered, collectAdvance.get(0),
						names.get("check_user_item_ok"), names.get("check_user_item_fail"), ""));
					continue;
				}
				// talk 段：页梯 = select{i} 出发的导航**图**（BFS 全分量，分支页不得被线性化），
				// 推进动作 = 段内唯一的推进按钮；两个不同推进 id 属形状二义，如实跳过整行。
				// Talk stage: the ladder is the nav graph reachable from select{i} (BFS); the advance is
				// the single advance button of the stage, and two distinct advances skip the row.
				List<Integer> ladder = new ArrayList<>(List.of(head.getValue()));
				Set<Integer> seen = new HashSet<>(ladder);
				List<Integer> queue = new ArrayList<>(ladder);
				List<Integer> advance = List.of();
				int tail = head.getValue();
				while (!queue.isEmpty()) {
					int cursor = queue.remove(0);
					tail = cursor;
					List<Integer> cursorButtons = questButtons.getOrDefault(cursor, List.of());
					advance = new ArrayList<>();
					for (int button : cursorButtons) {
						if (TALK_ADVANCE_IDS.contains(button)) {
							advance.add(button);
						}
					}
					if (!advance.isEmpty()) {
						break;
					}
					for (int button : cursorButtons) {
						if (COLLECT_ADVANCE_IDS.contains(button) || TALK_ADVANCE_IDS.contains(button)) {
							continue;
						}
						if (!ids.contains(button) || !seen.add(button)) {
							continue;
						}
						ladder.add(button);
						queue.add(button);
					}
				}
				if (advance.isEmpty()) {
					aborted = true;
					break;
				}
				if (advance.size() > 1) {
					bump(skipped, "multi_advance");
					aborted = true;
					break;
				}
				// 梯尾页的过场：推进动作附带 movie（16942 形）。 / The tail page's cut scene rides the
				// advance action.
				String movie = frozen.cutscenes().getOrDefault(questId, Map.of()).getOrDefault(tail, "");
				stages.add(new Stage("talk", ladder, advance.get(0), null, null, movie));
			}
			if (aborted) {
				continue;
			}
			List<String> got = new ArrayList<>();
			for (Stage stage : stages) {
				got.add(stage.kind());
			}
			List<String> wantedVisible = new ArrayList<>();
			for (String category : quest.categories()) {
				if (!List.of("hunt", "enterarea", "itemplay", "pvp").contains(category)) {
					wantedVisible.add(category);
				}
			}
			if (!got.equals(wantedVisible)) {
				bump(skipped, "stage_mismatch");
				continue;
			}
			List<String> columns = new ArrayList<>();
			for (Stage stage : stages) {
				if ("collect".equals(stage.kind())) {
					columns.add("collect:" + joinLadder(stage.ladder()) + ":" + stage.advance() + ":"
						+ stage.okPage() + ":" + stage.failPage());
					continue;
				}
				String column = "talk:" + joinLadder(stage.ladder()) + ":" + stage.advance();
				if (!stage.movie().isEmpty()) {
					column += ":" + stage.movie();
				}
				columns.add(column);
			}
			rows.add(questId + "\t" + entryPage + "\t" + String.join("\t", columns));
		}

		Path outFile = outputRoot.resolve(OUTPUT_TABLE);
		Files.createDirectories(outFile.getParent());
		List<String> out = new ArrayList<>(HEADER);
		out.addAll(rows);
		Files.writeString(outFile, String.join("\n", out) + "\n", StandardCharsets.UTF_8);
		System.out.println("QuestTalkCollectChainPagesGenerator: rows=" + rows.size()
			+ " dd_mixes=" + dd.size() + " skipped=" + skipped + " -> " + outFile);
	}

	private Path require(String relative) throws IOException {
		Path path = repo.resolve(relative);
		if (!Files.isRegularFile(path)) {
			throw new IOException("missing generation source: " + path);
		}
		return path;
	}

	/** 冻结事实：排除 id / 过场 (quest, 页 id → movie) / 刻意保留的 WITHHELD id。 / Frozen facts. */
	private record Facts(Set<Integer> exclusions, Map<Integer, Map<Integer, String>> cutscenes) {
	}

	private static Facts readFacts(Path path) throws IOException {
		Set<Integer> exclusions = new HashSet<>();
		Map<Integer, Map<Integer, String>> cutscenes = new HashMap<>();
		for (String line : Files.readAllLines(path, StandardCharsets.UTF_8)) {
			if (line.isBlank() || line.startsWith("#")) {
				continue;
			}
			String[] parts = line.split(",", -1);
			if (parts.length < 5) {
				throw new IOException("malformed frozen facts row: " + line);
			}
			int questId = Integer.parseInt(parts[1].strip());
			switch (parts[0].strip()) {
				case "exclude", "withheld" -> exclusions.add(questId);
				case "cutscene" -> cutscenes.computeIfAbsent(questId, key -> new HashMap<>())
					.put(Integer.parseInt(parts[2].strip()), parts[3].strip());
				default -> throw new IOException("unknown frozen facts kind: " + parts[0]);
			}
		}
		return new Facts(exclusions, cutscenes);
	}

	/** DD 表逐任务类别（小写，collectitem→collect）与接取类别；只留 eligible 的混合行。 / DD categories. */
	private static Map<Integer, DdQuest> readDataDriven(Path path) throws IOException {
		String xml = Files.readString(path, StandardCharsets.UTF_8);
		Map<Integer, DdQuest> out = new TreeMap<>();
		Matcher blocks = QUEST_BLOCK.matcher(xml);
		while (blocks.find()) {
			String block = blocks.group(1);
			Matcher idMatcher = QUEST_ID.matcher(block);
			if (!idMatcher.find()) {
				continue;
			}
			int questId = Integer.parseInt(idMatcher.group(1));
			List<String> categories = new ArrayList<>();
			Matcher progress = PROGRESS_CATEGORY.matcher(block);
			while (progress.find()) {
				String category = progress.group(1).strip().toLowerCase(java.util.Locale.ROOT);
				categories.add("collectitem".equals(category) ? "collect" : category);
			}
			Matcher acquire = ACQUIRE_CATEGORY.matcher(block);
			String acquireCategory = acquire.find() ? acquire.group(1).strip().toLowerCase(java.util.Locale.ROOT) : "";
			Set<String> kinds = new HashSet<>(categories);
			boolean eligible = kinds.stream()
				.allMatch(kind -> List.of("talk", "collect", "hunt", "enterarea", "itemplay", "pvp").contains(kind))
				&& (kinds.contains("talk") || kinds.contains("hunt")
					|| (kinds.contains("pvp") && kinds.contains("collect")))
				&& (kinds.contains("collect") || kinds.contains("enterarea")
					|| kinds.contains("itemplay") || kinds.contains("pvp"));
			if (eligible) {
				out.put(questId, new DdQuest(categories, acquireCategory));
			}
		}
		return out;
	}

	/** 客户端页表：quest → (页名 → 页 id) 与页 id 集。 / Client page registry. */
	private static void readPagesCsv(Path path, Map<Integer, Map<String, Integer>> byName,
		Map<Integer, Set<Integer>> ids) throws IOException {
		int lineNumber = 0;
		for (String line : Files.readAllLines(path, StandardCharsets.UTF_8)) {
			lineNumber++;
			if (lineNumber == 1 || line.isBlank()) {
				continue;
			}
			String[] fields = line.split(",", -1);
			if (fields.length < 7) {
				throw new IOException("malformed page row at line " + lineNumber);
			}
			int questId = Integer.parseInt(fields[0].strip());
			int pageId = Integer.parseInt(fields[6].strip());
			byName.computeIfAbsent(questId, key -> new LinkedHashMap<>()).putIfAbsent(fields[5], pageId);
			ids.computeIfAbsent(questId, key -> new HashSet<>()).add(pageId);
		}
	}

	/** 客户端按钮图：quest → (页 id → 动作 id 列表，保序且保留重复)。 / Client button graph. */
	private static Map<Integer, Map<Integer, List<Integer>>> readActionsCsv(Path path) throws IOException {
		Map<Integer, Map<Integer, List<Integer>>> buttons = new HashMap<>();
		int lineNumber = 0;
		for (String line : Files.readAllLines(path, StandardCharsets.UTF_8)) {
			lineNumber++;
			if (lineNumber == 1 || line.isBlank()) {
				continue;
			}
			String[] fields = line.split(",", -1);
			if (fields.length < 13) {
				throw new IOException("malformed action row at line " + lineNumber);
			}
			if (fields[12].isBlank()) {
				continue;
			}
			int questId = Integer.parseInt(fields[0].strip());
			int pageId = Integer.parseInt(fields[6].strip());
			buttons.computeIfAbsent(questId, key -> new HashMap<>())
				.computeIfAbsent(pageId, key -> new ArrayList<>())
				.add(Integer.parseInt(fields[12].strip()));
		}
		return buttons;
	}

	/** 注册表的 quest id 列（{@code #} 注释与空行跳过）。 / Quest-id column of a registry TSV. */
	private static Set<Integer> readIdColumn(Path path) throws IOException {
		Set<Integer> ids = new HashSet<>();
		for (String line : Files.readAllLines(path, StandardCharsets.UTF_8)) {
			if (line.isBlank() || line.startsWith("#")) {
				continue;
			}
			ids.add(Integer.parseInt(line.split("\t", -1)[0].strip()));
		}
		return ids;
	}

	private static Map<Integer, Integer> stageHeads(Map<String, Integer> names) {
		Map<Integer, Integer> heads = new TreeMap<>();
		for (Map.Entry<String, Integer> entry : names.entrySet()) {
			Matcher matcher = STAGE_HEAD.matcher(entry.getKey());
			if (matcher.matches()) {
				heads.put(Integer.parseInt(matcher.group(1)), entry.getValue());
			}
		}
		return heads;
	}

	private static String joinLadder(List<Integer> ladder) {
		StringBuilder builder = new StringBuilder();
		for (int page : ladder) {
			if (builder.length() > 0) {
				builder.append(" > ");
			}
			builder.append(page);
		}
		return builder.toString();
	}

	private static void bump(Map<String, Integer> counters, String kind) {
		counters.merge(kind, 1, Integer::sum);
	}

	private record DdQuest(List<String> categories, String acquireCategory) {
	}

	private record Stage(String kind, List<Integer> ladder, int advance, Integer okPage, Integer failPage,
		String movie) {
	}
}
