spring:
  main:
    banner-mode: "off"
    web-application-type: none

aion:
  game:
    startup:
      progress:
        enabled: true
  services:
    game:
      enabled: true
    login:
      enabled: true
    chat:
      enabled: true
    transport:
      mode: netty
