spring:
  main:
    banner-mode: "off"
    web-application-type: none

aion:
  services:
    game:
      enabled: true
    login:
      enabled: true
    chat:
      enabled: false
    transport:
      mode: netty
