spring:
  main:
    banner-mode: "off"
    log-startup-info: false
    web-application-type: none
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

aion:
  game:
    startup:
      progress:
        enabled: true
  services:
    game:
      enabled: true
    login:
      enabled: true
    chat:
      enabled: true
    transport:
      mode: netty
