<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="quest_data.xsd"/>
	<xs:include schemaLocation="../../data/static_data/global_types.xsd"/>
	<xs:include schemaLocation="../../data/static_data/import.xsd"/>
	<xs:element name="quest_scripts" type="QuestScripts"/>
	<xs:complexType name="QuestScripts">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="item_collecting" type="ItemCollectingData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="report_to" type="ReportToData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="monster_hunt" type="MonsterHuntData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="mentor_monster_hunt" type="MentorMonsterHuntData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="work_order" type="WorkOrdersData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="report_to_many" type="ReportToManyData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="relic_rewards" type="RelicRewardsData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="crafting_rewards" type="CraftingRewardsData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="kill_in_world" type="KillInWorldData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="skill_use" type="SkillUseData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="kill_spawned" type="KillSpawnedData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="item_order" type="ItemOrdersData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="data_driven_quest" type="DataDrivenQuestData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="fountain_rewards" type="FountainRewardsData" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DataDrivenQuestData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:sequence>
					<xs:element name="step" type="DataDrivenQuestStep" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="start_type" type="DataDrivenQuestStepType" use="required"/>
				<xs:attribute name="start_ids" type="IntListType"/>
				<xs:attribute name="start_dialog_id" type="xs:int"/>
				<xs:attribute name="end_npc_ids" type="IntListType"/>
				<xs:attribute name="world_id" type="xs:int"/>
				<xs:attribute name="reset_world_id" type="xs:int"/>
				<xs:attribute name="start_item_id" type="xs:int"/>
				<xs:attribute name="start_give_item_id" type="xs:int"/>
				<xs:attribute name="start_give_item_count" type="xs:int"/>
				<xs:attribute name="start_remove_item_id" type="xs:int"/>
				<xs:attribute name="start_remove_item_count" type="xs:int"/>
				<xs:attribute name="complete_on_start" type="xs:boolean" default="false"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="DataDrivenQuestStep">
		<xs:attribute name="type" type="DataDrivenQuestStepType" use="required"/>
		<xs:attribute name="ids" type="IntListType"/>
		<xs:attribute name="action_ids" type="IntListType"/>
		<xs:attribute name="delete_action_target" type="xs:boolean" default="false"/>
		<xs:attribute name="amount" type="xs:int"/>
		<xs:attribute name="dialog_id" type="xs:int"/>
		<xs:attribute name="advance_dialog_id" type="xs:int"/>
		<xs:attribute name="movie" type="xs:int"/>
		<xs:attribute name="world_id" type="xs:int"/>
		<xs:attribute name="item_id" type="xs:int"/>
		<xs:attribute name="give_item_id" type="xs:int"/>
		<xs:attribute name="give_item_count" type="xs:int"/>
		<xs:attribute name="remove_item_id" type="xs:int"/>
		<xs:attribute name="remove_item_count" type="xs:int"/>
	</xs:complexType>
	<xs:simpleType name="DataDrivenQuestStepType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TALK"/>
			<xs:enumeration value="COLLECT_ITEM"/>
			<xs:enumeration value="HUNT"/>
			<xs:enumeration value="ENTER_AREA"/>
			<xs:enumeration value="ENTER_WORLD"/>
			<xs:enumeration value="ACTION"/>
				<xs:enumeration value="ITEM_PLAY"/>
				<xs:enumeration value="GET_ITEM"/>
				<xs:enumeration value="WORLD_ACTIVE"/>
				<xs:enumeration value="SENSORY_COMPLETE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="QuestScriptData" abstract="true">
		<xs:attribute name="id" type="xs:int" use="required"/>
		<xs:attribute name="movie" type="xs:int" use="optional"/>
		<xs:attribute name="mission" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="retail" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:complexType name="ItemCollectingData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_ids" type="IntListType" default="0"/>
				<xs:attribute name="next_npc_id" type="xs:int" default="0"/>
				<xs:attribute name="action_item_ids" type="IntListType" default="0"/>
				<xs:attribute name="end_npc_ids" type="IntListType" default="0"/>
				<xs:attribute name="start_dialog_id" type="xs:int" default="0"/>
				<xs:attribute name="start_dialog_id2" type="xs:int" default="0"/>
				<xs:attribute name="item_id" type="xs:int" default="0"/>
				<xs:attribute name="check_ok_dialog_id" type="xs:int" default="5"/>
				<xs:attribute name="check_fail_dialog_id" type="xs:int" default="2716"/>
				<xs:attribute name="reward_dialog_id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="RelicRewardsData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_ids" type="IntListType" use="required"/>
				<xs:attribute name="relic_var1" type="xs:int" use="required"/>
				<xs:attribute name="relic_var2" type="xs:int" use="required"/>
				<xs:attribute name="relic_var3" type="xs:int" use="required"/>
				<xs:attribute name="relic_var4" type="xs:int" use="required"/>
				<xs:attribute name="relic_count" type="xs:int" default="1"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CraftingRewardsData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="skill_id" type="xs:int" use="required"/>
				<xs:attribute name="level_reward" type="xs:int" use="required"/>
				<xs:attribute name="end_npc_id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ReportToData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_ids" type="IntListType" use="required"/>
				<xs:attribute name="end_npc_ids" type="IntListType" use="required"/>
				<xs:attribute name="start_dialog_id" type="xs:int" default="0"/>
                <xs:attribute name="start_dialog_id2" type="xs:int" default="0"/>
				<xs:attribute name="item_id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="MonsterHuntData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:sequence>
					<xs:element name="monster" type="Monster" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="start_npc_ids" type="IntListType" default="0"/>
				<xs:attribute name="end_npc_ids" type="IntListType" default="0"/>
				<xs:attribute name="start_dialog_id" type="xs:int" default="0"/>
				<xs:attribute name="end_dialog_id" type="xs:int" default="0"/>
				<xs:attribute name="aggro_start_npcs" type="IntListType" default="0"/>
				<xs:attribute name="invasion_world" type="xs:int" default="0"/>
			    <xs:attribute name="reward" type="xs:boolean" default="false"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="MentorMonsterHuntData">
		<xs:complexContent>
			<xs:extension base="MonsterHuntData">
				<xs:attribute name="min_mente_level" type="xs:int" default="0"/>
				<xs:attribute name="max_mente_level" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="KillSpawnedData">
		<xs:complexContent>
			<xs:extension base="MonsterHuntData">
				<xs:sequence>
					<xs:element name="spawned_monster" type="SpawnedMonster" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ReportToManyData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:sequence>
					<xs:element name="npc_infos" type="NpcInfos" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="start_npc_ids" type="IntListType" default="0"/>
				<xs:attribute name="start_item_id" type="xs:int" default="0"/>
				<xs:attribute name="start_dialog_id" type="xs:int" default="1011"/>
				<xs:attribute name="end_dialog_id" type="xs:int" default="2375"/>
				<xs:attribute name="end_npc_ids" type="IntListType" use="required"/>
				<xs:attribute name="timeout_seconds" type="xs:nonNegativeInteger" default="0"/>
				<xs:attribute name="timeout_start_var" type="xs:nonNegativeInteger" default="0"/>
				<xs:attribute name="timeout_reset_var" type="xs:nonNegativeInteger" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="NpcInfos" >
		<xs:attribute name="var" type="xs:int" use="required"/>
		<xs:attribute name="npc_id" type="xs:int" use="required"/>
		<xs:attribute name="quest_dialog" type="xs:int" use="required"/>
		<xs:attribute name="close_dialog" type="xs:int" default="0"/>
		<xs:attribute name="movie" type="xs:int" default="0"/>
	</xs:complexType>
	<xs:complexType name="WorkOrdersData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:sequence>
					<xs:element name="give_component" type="QuestItems" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="start_npc_ids" type="IntListType" use="required"/>
				<xs:attribute name="recipe_id" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Monster">
		<xs:attribute name="var" type="xs:int" use="required"/>
		<xs:attribute name="start_var" type="xs:int" default="0"/>
		<xs:attribute name="end_var" type="xs:int" use="required"/>
		<xs:attribute name="npc_ids" type="IntListType" use="required"/>
	</xs:complexType>
	<xs:complexType name="SpawnedMonster">
		<xs:complexContent>
			<xs:extension base="Monster">
				<xs:attribute name="spawner_object" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="KillInWorldData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_ids" type="IntListType" default="0"/>
				<xs:attribute name="end_npc_ids" type="IntListType" use="required"/>
				<xs:attribute name="worlds" type="IntListType" default="0"/>
				<xs:attribute name="amount" type="xs:int" use="required"/>
				<xs:attribute name="invasion_world" type="xs:int" default="0"/>
				<xs:attribute name="reward_dialog_id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ItemOrdersData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_item_id" type="xs:int" use="required"/>
				<xs:attribute name="talk_npc_id1" type="xs:int" default="0"/>
				<xs:attribute name="talk_npc_id2" type="xs:int" default="0"/>
				<xs:attribute name="end_npc_id" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="FountainRewardsData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_ids" type="IntListType" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="SkillUseData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:sequence>
					<xs:element name="skill" type="QuestSkillData" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="start_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="end_npc_id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="QuestSkillData">
		<xs:attribute name="ids" type="IntListType" use="required"/>
		<xs:attribute name="start_var" type="xs:int" default="0"/>
		<xs:attribute name="end_var" type="xs:int" use="required"/>
		<xs:attribute name="var_num" type="xs:int" default="0"/>
	</xs:complexType>
</xs:schema>
