#  背包设置
#  CUBE SETTINGS

# 背包起始大小
# Cube Start Size
# 默认值: 0 / 最大: 15 / Default: 0 / Max size: 15
gameserver.cube.size = 15

# 游戏内商城限制
# INGAME SHOP LIMITS

# 游戏内商城限制
# InGameShop Limit
# 启用或禁用游戏内商城限制
# Enable od Disable InGameShop Limits
# 默认值: false / Default: false
gameserver.gameshop.limit = false

# 默认游戏内商城分类
# Default InGameShop Categories
# 天族: 0 / Elyos: 0
# 魔族: 1 / Asmodian: 1
gameserver.gameshop.category = 0

# 游戏内商城时间限制
# InGameShop Time Limits
# 默认值: 60 / Default: 60
gameserver.gameshop.limit.time = 60
