# 高阶守护者配置:
# High Daeva Config's:

# 最大创造力点数
# Max Creativity Points
# 默认值: 1000 / Default: 1000
gameserver.max.cp.limit = 1000

# 高阶守护者物品启用:
# Item ArchDaeva enable:

# 这是针对成为高阶守护者玩家的自定义功能：
# This is custom function for players who's became ArchDaeva
# 装备非高阶守护者物品时，物品属性约降低 20%
# Equipping an item not intended for an ArchDaeva reduces its stats by about 20%
# 默认值: true / Default: true
gameserver.item.not.for.highdaeva.enable = true
