# 高阶守护者配置:
# High Daeva Config's:

# 最大创造力点数
# Max Creativity Points
# 默认值: 1000 / Default: 1000
gameserver.max.cp.limit = 1000

# 大天使物品启用:
# Item ArchDaeva enable:

# 这是针对成为大天使玩家的自定义功能：
# This is custom function for players who's became ArchDaeva
# 装备非大天使物品时，物品属性约降低 20%
# equip item not for ArchDave will decrease item's stats around 20%
# 默认值: true / Default: true
gameserver.item.not.for.highdaeva.enable = true
