# 交易行配置:
# "Broker" Properties:

# 处罚
# Punishment
# 0 - 仅记录日志 / add log record
# 1 - 记录日志并踢出玩家 / log and kick player from game
gameserver.broker.anti.hack.punishment = 0

# 交易行商品上架多少天后标记为过期
# Number of days before a broker item expires
# 默认值: 8 天 / Default: 8-days
gameserver.broker.items.expire.time = 8
