# 自定义配置

# 登录服务器信息（GM 响应窗口）
# Login Server Info (GM Response Window)

# 默认值: false / Default: false
gameserver.loginserver.info = false

# 按世界 ID 掉落 PvE 点数
# PvE Toll Drop On World ID

# 启用 Norsvold/Iluma 点数奖励
# Enable Toll Reward for Norsvold/Iluma
# 默认值: false / Default: false
gameserver.pve.toll.rewarding.enable = true

# PvE 点数概率
# PvE Toll Chance
# 默认值: 50 / Default: 50
# 数值越小概率越高 / Less is more!
gameserver.pve.toll.reward.chance = 10

# PvE 点数数量
# PvE Toll Quantity
# 默认值: 5 / Default: 5
gameserver.pve.toll.reward.quantity = 5

# PvE 点数世界 ID
# PvE Toll World ID
# 默认值: 220110000 / Norsvold
# Default: 220110000 / Norsvold
# 默认值: 210100000 / Iluma
# Default: 210100000 / Iluma
gameserver.pve.toll.reward.worldid =220110000,210100000,301640000,301630000,220100000,210090000,302330000,301631000,600050000

# 安息能量 / Energy Of Repose:

# 默认值: true / Default: true
gameserver.energy.of.repose.enable = true

# 保护者/征服者 / Protector/Conqueror:

gameserver.protector.conqueror.enable = false
gameserver.protector.conqueror.handled.worlds = 210020000,210040000,210130000,210060000,210070000,210100000,220020000,220040000,220050000,220140000,220080000,220110000
gameserver.protector.conqueror.kills.refresh = 1
gameserver.protector.conqueror.kills.decrease = 1
gameserver.protector.conqueror.level.diff = 10
gameserver.protector.conqueror.1st.rank.kills = 5
gameserver.protector.conqueror.2nd.rank.kills = 10

# 裂隙 / Rifts:

gameserver.rift.enable = true
gameserver.rift.duration = 1

# [佐西夫钢铁之战 2.1] / [Zorshiv Dredgion 2.1]

gameserver.zorshiv.dredgion.enable = true
gameserver.zorshiv.dredgion.duration = 1

# [熔火之王] / [Moltenus]

gameserver.moltenus.enable = false
gameserver.moltenus.duration = 1

# [争议之地] 3.0 / [Dispute Land] 3.0

gameserver.dispute.land.enable = true
gameserver.dispute.land.schedule = 0 0 */4 ? * *
gameserver.dispute.land.duration = 1

# [次元漩涡] 3.9 / [Dimensional Vortex] 3.9

gameserver.vortex.enable = true
gameserver.vortex.duration = 1

# [贝里特拉入侵] 4.7 / [Beritra Invasion] 4.7

gameserver.beritra.enable = true
gameserver.beritra.duration = 1

# [代理人之战] 4.7 / [Agent Fight] 4.7

gameserver.agent.enable = false
gameserver.agent.duration = 1

# [狂暴阿诺哈] 4.7 / [Berserk Anoha] 4.7

gameserver.anoha.enable = false
gameserver.anoha.duration = 1

# [S.v.S] 4.7
# [潘尼斯特拉] 4.7 / [Panesterra] 4.7

gameserver.svs.enable = true
gameserver.svs.duration = 1

# [R.v.R] 4.9
# [战舰入侵] 5.0 / [Warship Invasion] 5.0

gameserver.rvr.enable = true
gameserver.rvr.duration = 1

# [现场演唱会场] 4.3 / [Live Party Concert Hall] 4.3

gameserver.iu.enable = false
gameserver.iu.schedule = 0 0 */4 ? * *
gameserver.iu.duration = 1

# [噩梦马戏团] 4.3 / [Nightmare Circus] 4.3

gameserver.nightmare.circus.enable = false
gameserver.nightmare.circus.duration = 1

# [动态裂隙] / [Dynamic Rift]
# [术古商人联盟] / [Shugo Merchant League]

# 动态裂隙 / Dynamic Rift
gameserver.dynamic.rift.enable = false
gameserver.dynamic.rift.dragon.schedule = 0 0 */2 ? * *
gameserver.dynamic.rift.indratoo.schedule = 0 0 */2 ? * *
gameserver.dynamic.rift.duration = 1
# 术古商人联盟 / Shugo Merchant League
gameserver.shugo.merchant.league.schedule = 0 0 */2 ? * *

# [永恒之塔] / [Tower Of Eternity]

# 永恒之塔 / Tower Of Eternity
gameserver.tower.of.eternity.enable = true
gameserver.tower.of.eternity.schedule = 0 0 */1 ? * *
gameserver.tower.of.eternity.duration = 1

# [征服/供奉 4.8] / [Conquest/Offering 4.8]

gameserver.conquest.enable = true
gameserver.conquest.duration = 1

# [伊迪安深渊] 4.8 / [Idian Depths] 4.8

gameserver.idian.depths.enable = false
gameserver.idian.depths.schedule = 0 0 */6 ? * *
gameserver.idian.depths.duration = 1

# [副本裂隙 4.9] / [Instance Rift 4.9]

gameserver.instance.rift.enable = true
gameserver.instance.rift.duration = 24

# [基地奖励] / [Base Rewards]

gameserver.base.rewards.enable = true

# 渐进经验 / Xp Progressive:

# 默认值: false / Default: false
# 若无法使用“渐进经验”，请使用经典倍率
# if you cannot use the "progressive xp" so use the classic rates.
# 若决定使用“渐进经验”，请将 rates.properties 中所有倍率设为 x1
# But if you decide use the "progressive xp", so put x1 on all rates in "rates.properties"
# 可在以下位置的 RewardType 中修改“经验数值”：
# You can change "xp number" in "RewardType" in:
# src\com\aionemu\gameserver\model\gameobjects\player\RewardType.java
gameserver.enable.exp.progressive.book = false
gameserver.enable.exp.progressive.quest = false
gameserver.enable.exp.progressive.ap.npc = false
gameserver.enable.exp.progressive.hunting = false
gameserver.enable.exp.progressive.ap.player = false
gameserver.enable.exp.progressive.group.hunting = false

# [重连绑定点] / [Reconnect Bind Point]

# 默认值: true / Default: true
# 在官服 "KR/RU/CHS/JAP/NA/EU" 上
# On official server "KR/RU/CHS/JAP/NA/EU"
# 玩家每次从服务器断开后
# every time a player disconnect from server.
# 重连后总是传送到“绑定点”
# After reconnect is he always teleport to "Bind Point"
gameserver.reconnect.to.bind.point = false

# [自动掉落基纳] / [Auto Drop Kinah]

# 默认值: false / Default: false
# 玩家每次击杀怪物/BOSS 时获得“基纳”
# Players earn "Kinah" every time they kill mob/boss.
# 若玩家在“副本”中击杀怪物/BOSS，
# If a player in "Instance" kill a mob/boss,
# 将根据其等级获得基纳
# he will earn kinah based on its level.
gameserver.auto.kinah.enabled = true

# 神石发动倍率与判定冷却。
# Godstone activation rate and evaluation cooldown.
gameserver.rates.godstone.activation.rate = 1.0
gameserver.rates.godstone.evaluation.cooldown_millis = 750

# 启用挑战任务
# Enable challenge tasks
# 默认值: true / Default: true
gameserver.challenge.tasks.enabled = true

# 登录时显示高级账号详情
# Show premium account details on login
# 默认值: false / Default: false
gameserver.premium.notify.enable = true

# 玩家成功强化物品到 15/20 时启用公告
# Enable announce when a player succes enchant item 15/20
# 默认值: true / Default: true
gameserver.enchant.announce.enable = true

# 启用阵营间对话
# Enable speaking between factions
# 默认值: false / Default: false
gameserver.chat.factions.enable = false

# 使用密语的最低等级
# Minimum level to use whisper
# 默认值: 10 / Default: 10
gameserver.chat.whisper.level = 1

# 允许敌对阵营在敌方领地绑定
# Allow opposite factions to bind in enemy territories
# 默认值: false / Default: false
gameserver.cross.faction.binding = false

# 启用无需任务的二次转职
# Enable second class change without quest
# 默认值: false / Default: false
gameserver.simple.secondclass.enable = false

# 禁用连招触发率（连招技能 100% 成功）
# Disable chain trigger rate (chain skill with 100% success)
# 默认值: true / Default: true
gameserver.skill.chain.triggerrate = true

# 启用骑乘限制
# Enable ride restriction
# 默认值: true / Default: true
gameserver.ride.restriction.enable = false

# 使用染色命令的价格
# The price for using dye command
# 默认值: 1000000 / Default: 1000000
gameserver.admin.dye.price = 10

# 默认玩家飞行时间
# Default player fly time
# 默认值: 60（1 分钟） / Default: 60 (1 minute)
gameserver.base.flytime = 600

# 魔法增幅有效上限
# Default: 6500
gameserver.magicboost.cap = 6500

# 在导师组中禁用 AP
# Enable no AP in mentored group.
# 默认值: false / Default: false
gameserver.noap.mentor.group = false

# 启用显示“任务/对话 ID”
# Enable Show "Quest/Dialog ID"
# 默认值: false / Default: false
# 开发用: true / For Dev: true
gameserver.dialog.show.id = true

# 副本配置 / Instances config's:

# 启用副本（临时配置，直至副本系统成熟）
# Enable instances (temporary config till instances will be mature)
# 默认值: true / Default: true
gameserver.instances.enable = true

# 启用副本怪物始终对玩家仇恨并忽略等级
# Enable instances mob always aggro player ignoring level
# 默认值: 字符串 300050000,300060000 等 / Default: String 300050000,300060000 etc etc
# 添加 instanceId 使怪物始终对玩家仇恨并忽略等级
# Add instanceId for mob always aggro player ignoring level
gameserver.instances.mob.aggro = 300030000,300040000,300050000,300060000,300070000,300080000,300090000,300100000,300110000,300120000,300130000,300140000,300150000,300160000,300170000,300190000,300200000,300210000,300220000,300230000,300240000,300241000,300250000,300280000,300300000,300310000,300320000,300350000,300360000,300420000,300430000,300440000,300450000,300460000,300480000,300510000,300520000,300540000,300550000,300560000,300570000,300590000,300600000,300610000,300620000,300630000,300700000,300800000,301100000,301110000,301120000,301130000,301140000,301160000,301200000,301210000,301220000,301230000,301240000,301250000,301260000,301270000,301280000,301290000,301300000,301310000,301320000,301330000,301340000,301350000,301360000,301370000,301380000,301390000,301400000,301500000,301510000,301520000,301540000,301550000,301560000,301570000,301590000,301600000,301610000,301620000,301630000,301631000,301640000,301650000,301660000,301670000,301680000,301700000,301720000,302000000,302100000,302110000,302200000,302300000,302330000,302340000,302350000,302400000,310030000,310040000,310050000,310080000,310090000,310100000,310110000,310160000,320030000,320040000,320050000,320080000,320090000,320100000,320110000,320120000,320130000,320150000,320160000,400030000

# 副本内决斗
# Duel in Instance
# 默认值: true / Default: true
gameserver.instance.duel.enable = true

# Web 配置 / Web config's:

# 用于从 Web 直接正确添加物品的奖励服务
# RewardService used to add items directly and correctly from web
# 默认值: false / Default: false
gameserver.reward.service.enable = true

# 限制配置 / Limits config:

# 启用限制
# Enable limits
# 默认值: true / Default: true
gameserver.limits.enable = false

# 限制更新时间
# Limit update time
# 默认值: 每天 00:00 / Default: 00:00 everyday
gameserver.limits.update = 0 0 0 * * ?

# 出售限制倍率
# Sell Limits Rate
# 默认值: 1 / Default: 1
gameserver.limits.rate = 1

# 上限配置 / Cap Config's:

# 启用基纳上限
# Enable Kinah Capping
# 默认值: false / Default: false
gameserver.enable.kinah.cap = false
# 基纳上限值
# Cap value for Kinah
# 默认值: 10.000.000.000 / Default: 10.000.000.000
gameserver.kinah.cap.value = 10000000000

# 启用露娜上限
# Enable Luna Capping
# 默认值: false / Default: false
gameserver.enable.luna.cap = false
# 露娜上限值
# Cap value for Luna
# 默认值: 9.999.999 / Default: 9.999.999
gameserver.luna.cap.value = 9999999

# 旧名称配置 / OldNames config's:

# 禁用通过优惠券使用旧名称的限制
# Disable prevention using old names with coupon
# 默认值: false / Default: false
gameserver.oldnames.coupon.disable = true

# 禁用通过管理员命令使用旧名称的限制
# Disable prevention using old names with admin command
# 默认值: true / Default: true
gameserver.oldnames.command.disable = true

# 容量配置 / Size config's:

# 好友列表容量（最大 90）
# Friendlist size (max 90)
# 默认值: 90 / Default: 90
gameserver.friendlist.size = 90

# 允许配置玩家可接取的基础任务数量上限
# Allow to configure size limit of basic quests that player can get up
# 默认值: 50 / Default: 50
gameserver.basic.questsize.limit = 50

# 搜索配置 / Search config's:

# 启用搜索敌对阵营玩家
# Enable searching players of opposite faction
# 默认值: false / Default: false
gameserver.search.factions.mode = false

# 搜索玩家时启用列出 GM
# Enable list gm when searching players
# 默认值: false / Default: false
gameserver.search.gm.list = false

# 登出后欧比斯变形
# Abyss Xform after logout
# 启用或禁用欧比斯变形在登出后继续倒计时
# Enable or Disable counting down of duration after logout of Abyss transformations

gameserver.abyssxform.afterlogout = true

# .faction 命令 / .faction Command

# 免费使用
# Free use
gameserver.faction.free = true
gameserver.faction.prices = 10000
# 启用该命令
# Enable the command
gameserver.faction.cmdchannel = true
# 启用聊天服务器频道
# Enable chat servers channels
gameserver.faction.chatchannels = false
# 世界频道使用费用（AP）
# World Channel use Costs (AP)
gameserver.worldchannel.costs = 0

# 自定义 PvE/PK 标签 / Custom Pve/Pk Tags

# PvE 模式标签（护盾标签）
# Tag For PvE Mode ( SHIELD TAG )
gameserver.pve.tag = \uE06b %s
# PK（玩家击杀）模式标签（骷髅标签）
# Tag for PK (PlayerKill) Mode ( SKULL TAG )
gameserver.pk.tag = \uE022 %s

# 盗贼公会 5.0.6 / Thieves Guild 5.0.6

# 默认值: false / Default: false
gameserver.thieves.guild.enable = false

# 启用自动能量碎片 / ENABLE AUTO POWERSHARD

gameserver.enable.auto.powershard = false

# 允许按 NpcId 禁用传送员和飞行传送员
# Allow's you to disable Teleporter and Flight transporter by NpcId
# 例如 皮拉托斯 (Esterra)、库纳克 (Nosra) : 805917,805882
# Example Pilatos (Esterra), Kunak (Nosra) : 805917,805882
# 默认值: gameserver.disable.teleport.npcs = 0 / Default: gameserver.disable.teleport.npcs = 0

gameserver.disable.teleport.npcs = 0
