# 强化配置:
# ENCHANT CONFIG:

# 镶嵌魔力石:
# Socket Manastone:
# 默认值: 50 / Default: 50
gameserver.socket.manastone = 100

# 强化物品:
# Enchant Item:
# 默认值: 50 / Default: 50
gameserver.enchant.item = 90

# 统一强化物品基纳消耗:
# Unified Enchant Item Kinah:
# 默认值: -1（使用当前品质/等级价格表） / Default: -1 (use current quality/level price table)
gameserver.enchant.item.kinah = 20000

# 装备最大强化等级:
# Max Equipment Enchant Level:
# 默认值: 30 / Default: 30
gameserver.enchant.equipment.max.level = 30

# 强化羽饰:
# Enchant Plume:
# 默认值: 50 / Default: 50
gameserver.enchant.plume = 90

# 强化手镯:
# Enchant Bracelet:
# 默认值: 50 / Default: 50
gameserver.enchant.bracelet = 90

# 强化饰品:
# Enchant Accessory:
# 默认值: 50 / Default: 50
gameserver.enchant.accessory = 90

# 强化烙印:
# Enchant Stigma:
# 默认值: 50 / Default: 50
gameserver.enchant.stigma = 90

# 强化施法速度物品:
# Enchant Cast Speed Item:
# 默认值: 4000 / Default: 4000
gameserver.enchant.cast.speed = 500

# 清理镶嵌过载魔力石的物品
# Clean items with overloaded manastones
# 默认值: false / Default: false
gameserver.manastone.clean = false
