# FFA 启用/禁用
# FFA Enable/Disable

# 启用 FFA
# Enable FFA
# 默认值: false / Default: false
gameserver.pvp.mod.ffa.enabled = false

# FFA 连杀通行费
# FFA Spree Toll

# FFA 连杀通行费数量
# FFA Spree Toll Quantity
# 默认值: 10 / Default: 10
gameserver.pvp.mod.ffa.spree.toll.quantity = 10

# FFA 连杀奖励
# FFA Spree Reward

# FFA 连杀奖励物品
# FFA Spree Reward Item
# 默认值: 166030005 / Default: 166030005
gameserver.pvp.mod.ffa.spree.reward.item = 166030005

# FFA 连杀称号
# FFA Spree Names

# 默认值: <is now on a Killing Spree> ! / Default: <is now on a Killing Spree> !
gameserver.pvp.mod.ffa.spree1 = <is now on a Killing Spree> !
# 默认值: <is now on Rampage> ! / Default: <is now on Rampage> !
gameserver.pvp.mod.ffa.spree2 = <is now on Rampage> !
# 默认值: <is now Dominating> ! / Default: <is now Dominating> !
gameserver.pvp.mod.ffa.spree3 = <is now Dominating> !
# 默认值: <Unstoppable> ! / Default: <Unstoppable> !
gameserver.pvp.mod.ffa.spree4 = <Unstoppable> !
# 默认值: <CHUUCHUU MUTHAFAKAAASS> ! / Default: <CHUUCHUU MUTHAFAKAAASS> !
gameserver.pvp.mod.ffa.spree5 = <CHUUCHUU MUTHAFAKAAASS> !
# 默认值: <is now Getting Crazzyyy> ! / Default: <is now Getting Crazzyyy> !
gameserver.pvp.mod.ffa.spree6 = <is now Getting Crazzyyy> !
# 默认值: <is now GODLIKE> ! / Default: <is now GODLIKE> !
gameserver.pvp.mod.ffa.spree7 = <is now GODLIKE> !
# 默认值: <is now on WICKED SICKKKKKK> ! / Default: <is now on WICKED SICKKKKKK> !
gameserver.pvp.mod.ffa.spree8 = <is now on WICKED SICKKKKKK> !
# 默认值: <Really knows how to kill players> ! / Default: <Really knows how to kill players> !
gameserver.pvp.mod.ffa.spree9 = <Really knows how to kill players> !
# 默认值: <IS NOW A TRUE PVP FIGHTER> ! / Default: <IS NOW A TRUE PVP FIGHTER> !
gameserver.pvp.mod.ffa.spree10 = <IS NOW A TRUE PVP FIGHTER> !
