# 队伍相关配置:
# Group config's:

# 队员断线后被移出队伍的时间（秒）
# Time in seconds after a group member is removed after disconnect
# 默认值: 600（10 分钟） / Default: 600 (10 minutes)
gameserver.playergroup.removetime = 600

# 队伍成员与击杀怪物之间可获得经验的最大距离
# Maximum distance between killed monster and party member to receive XP
# 默认值: 100 / Default: 100
gameserver.playergroup.maxdistance = 100

# 允许邀请其他阵营玩家加入队伍
# Enable inviting to group player from other faction
# 默认值: false / Default: false
gameserver.group.inviteotherfaction = false

# 联盟相关配置:
# Alliance config's:

# 联盟成员断线后被移出联盟的时间（秒）
# Time in seconds after a alliance member is removed after disconnect
# 默认值: 600（10 分钟） / Default: 600 (10 minutes)
gameserver.playeralliance.removetime = 600

# 允许邀请其他阵营玩家加入联盟
# Enable inviting to alliance player from other faction
# 默认值: false / Default: false
gameserver.playeralliance.inviteotherfaction = false
