# 游戏内商城配置:
# In game shop config's:

# 别忘了在启动器添加 -ingameshop
# Don't forget add on launcher -ingameshop

# 启用游戏内商城
# Enable in game shop
# 默认值: false / Default: false
gameserver.ingameshop.enable = true

# 启用跨阵营礼物系统
# Enable gift system between factions
# 默认值: false / Default: false
gameserver.ingameshop.gift = false

# 是否允许赠送礼物
# allows gifts at all or no
gameserver.ingameshop.allow.gift = false
