# 日志配置
# 高级日志 / Advanced logging

# 启用高级日志可在日志中记录额外数据
# Enabling Advanced logging may allow additional datas into logs
# （例如：物品名称）
# (For Example: Item Name)
# 默认值: false / Default: false
gameserver.enable.advanced.logging = true

# 日志配置 / Logging config's:

# 启用审计日志
# Enable audit logging
# 默认值: true / Default: true
gameserver.log.audit = true

# 启用聊天日志
# Enable chat logging
# 默认值: true / Default: true
gameserver.log.chat = true

# 启用阵营命令日志
# Enable Faction Command logging
# 默认值: false / Default: false
gameserver.log.faction = true

# 启用 GM 审计日志
# Enable gmaudit logging
# 默认值: true / Default: true
gameserver.log.gmaudit = true

# 启用物品日志
# Enable item logging
# 默认值: true / Default: true
gameserver.log.item = true

# 启用击杀日志
# Enable kill logging
# 默认值: false / Default: false
gameserver.log.kill = true

# 启用代练日志
# Enable PowerLeveling logging
# 默认值: false / Default: false
gameserver.log.pl = true

# 启用攻城日志
# Enable siege logging
# 默认值: false / Default: false
gameserver.log.siege = true

# 启用房屋拍卖结果日志
# Enable house auction result logging
# 默认值: true / Default: true
gameserver.log.auction = true
