# 会员配置

# 会员配置 / Membership config's:

# 玩家申请的称号
# Title ask by player.
gameserver.player.tag.30 = <Gardien De Zoo> %s

# 本文件包含高级会员玩家的设置
# This file contains settings for premium membership players
#  掩码（若无额外说明）
#  Masks (if no additional comments)
#  10 - 禁用 / disabled
#  3-9 - 会员 3-9 / membership 3-9
#  2 - VIP（会员 2） / vip (membership 2)
#  1 - 高级（会员 1） / premium (membership 1)
#  0 - 所有玩家 / all players
# 副本称号要求
# Instances Title Requirement"
# 默认值: 10 / Default: 10
gameserver.instances.title.requirement = 10

# 副本种族要求
# Instances Race Requirement"
# 默认值: 10 / Default: 10
gameserver.instances.race.requirement = 10

# 副本等级要求
# Instances Level Requirement"
# 默认值: 10 / Default: 10
gameserver.instances.level.requirement = 10

# 副本组队要求
# Instances Group Requirement"
# 默认值: 10 / Default: 10
gameserver.instances.group.requirement = 10

# 副本任务要求
# Instances Quest Requirement"
# 默认值: 10 / Default: 10
gameserver.instances.quest.requirement = 10

# 副本物品要求
# Instances Item Requirement"
# 默认值: 10 / Default: 10
gameserver.instances.item.requirement = 10

# 激活副本冷却
# Active Instances Cooldowns"
# 默认值: 10 / Default: 10
gameserver.instances.cooldown = 10

# “所有物品均可存入仓库”
# "All Items Can Be Storable In Warehouse"
# 默认值: 10 / Default: 10
gameserver.store.wh.all = 10

# “所有物品均可存入账号仓库”
# "All Items Can Be Storable In Account Warehouse"
# 默认值: 10 / Default: 10
gameserver.store.accountwh.all = 10

# “所有物品均可存入军团仓库”
# "All Items Can Be Storable In Legion Warehouse"
# 默认值: 10 / Default: 10
gameserver.store.legionwh.all = 10

# “所有物品可交易”
# "All Items Can Be Tradeable"
# 默认值: 10 / Default: 10
gameserver.trade.all = 0

# 灵魂绑定“灵魂绑定物品可交易”
# Soulbound "Items Soulbind Can Be Tradeable"
# 默认值: 10 / Default: 10
gameserver.disable.soulbind = 10

# 所有“物品可改装”
# All "Items Can Be Remodelable"
# 默认值: 10 / Default: 10
gameserver.remodel.all = 0

# 所有“表情可用”
# All "Emotions Available"
# 默认值: 10 / Default: 10
gameserver.emotions.all = 0

# 启用 10 个额外称号
# Enable 10 additional titles
# 默认值: 10 / Default: 10
gameserver.titles.additional.enable = 0

# 普通/高级魔石槽无需任务
# Not require quest for normal/advanced stigma slots
# 默认值: 10 / Default: 10
gameserver.quest.stigma.slot = 10

# 禁用“灵魂病”
# Disable "Soulsickness"
# 默认值: 10 / Default: 10
gameserver.soulsickness.disable = 10

# 启用“魔石技能自动学习”
# Enable "Stigma Skills Auto Learn"
# 默认值: 10 / Default: 10
gameserver.autolearn.stigma = 10

# 启用“每账号额外角色”
# Enable "Additional Characters Per Account"
# 默认值: 10 / Default: 10
gameserver.character.additional.enable = 10

# 启用“高级好友列表”
# Enable "Advanced Friendlist"
# 默认值: 10 / Default: 10
gameserver.advanced.friendlist.enable = 10

# 会员选项 / Membership Options:

# 该会员等级的角色数量（最大 8）
# Count of characters for this membership (max 8)
# 默认值: 8 / Default: 8
gameserver.character.additional.count = 8

# 好友列表容量（最大 90）
# Friendlist size (max 90)
# 默认值: 90 / Default: 90
gameserver.advanced.friendlist.size = 90

# 会员标签 / Membership Tags

# 启用会员标签
# Enable Membership Tags
# 默认值: true / Default: true
gameserver.membership.tag.display.enable = true

# 不同标签
# Different tags
# 默认高级: \uE02D %s (\uE024 %s) / Default Premium: \uE02D %s (\uE024 %s)
# 默认 VIP: \uE02E %s (\uE023 %s) / Default VIP: \uE02E %s (\uE023 %s)
# 可选:
# Possible:
# gameserver.membership.tag.premium = \uE024 %s
# gameserver.membership.tag.vip = \uE023 %s
gameserver.membership.tag.premium = \uE06A %s
gameserver.membership.tag.vip = \uE055 %s
