# 排行榜相关配置:
# Ranking config's:

# [欧比斯排名更新设置]
# [Abyss Rank Update setting]
# 默认值: true / Default: true
# true : 按小时更新欧比斯排名 / Abyss Rank Update hour
# false : 按分钟更新欧比斯排名 / Abyss Rank Update minute
gameserver.top.ranking.update.setting = true

# [欧比斯排名更新（小时）]
# [Abyss Rank Update hour]
# 默认值: 0 0 */2 ? * * / Default: 0 0 */2 ? * *
gameserver.top.ranking.update.hour = 0 0 */2 ? * *

# [欧比斯排名更新（分钟）]
# [Abyss Rank Update minute]
# 默认值: 10 分钟 / Default: 10 min
gameserver.top.ranking.update.minute = 10

# 非活跃玩家的欧比斯排名限制
# Abyssrank limitation for inactive players
# 若该值大于零，则仅过去 X 天内活跃过的玩家可作为候选
# If this value is higher than zero, only players,
# who were active in the last X days are possible candidates
# 默认值: 7 / Default: 7

gameserver.top.ranking.max.offline.days = 7
