# 倍率配置

# 商城奖励倍率 / IngameShop Reward Rates:

gameserver.rate.regular.toll.reward = 1
gameserver.rate.premium.toll.reward = 2
gameserver.rate.vip.toll.reward = 3

# 经验倍率 / XP Rates:

gameserver.rate.regular.xp = 1
gameserver.rate.premium.xp = 1
gameserver.rate.vip.xp = 1

# 组队经验倍率 / Group XP Rates:

gameserver.rate.regular.group.xp = 1
gameserver.rate.premium.group.xp = 1
gameserver.rate.vip.group.xp = 1

# 任务经验倍率 / Quest XP Rates:

gameserver.rate.regular.quest.xp = 1
gameserver.rate.premium.quest.xp = 1
gameserver.rate.vip.quest.xp = 1

# 采集经验倍率 / Gathering XP Rates:

gameserver.rate.regular.gathering.xp = 2
gameserver.rate.premium.gathering.xp = 2
gameserver.rate.vip.gathering.xp = 3

# 采集次数倍率 / Gathering Count Rates:

gameserver.rate.regular.gathering.count = 20
gameserver.rate.premium.gathering.count = 20
gameserver.rate.vip.gathering.count = 20

# 制作经验倍率 / Crafting XP Rates:

gameserver.rate.regular.crafting.xp = 20
gameserver.rate.premium.crafting.xp = 20
gameserver.rate.vip.crafting.xp = 20

# 宠物喂养倍率 / Pet Feeding Rates:

gameserver.rate.regular.pet.feeding = 1
gameserver.rate.premium.pet.feeding = 2
gameserver.rate.vip.pet.feeding = 3

# 任务基纳倍率 / Quest Kinah Rates:

gameserver.rate.regular.quest.kinah = 1
gameserver.rate.premium.quest.kinah = 1
gameserver.rate.vip.quest.kinah = 1

# 任务 AP 倍率 / Quest AP Rates:

gameserver.rate.regular.quest.ap = 1
gameserver.rate.premium.quest.ap = 1
gameserver.rate.vip.quest.ap = 1

# 任务 GP 倍率 / Quest GP Rates:

gameserver.rate.regular.quest.gp = 1
gameserver.rate.premium.quest.gp = 1
gameserver.rate.vip.quest.gp = 1

# 任务欧比斯登陆倍率 / Quest Abyss Landing Rates:

gameserver.rate.regular.quest.abyss_op = 20
gameserver.rate.premium.quest.abyss_op = 20
gameserver.rate.vip.quest.abyss_op = 20

# 任务经验加成倍率 / Quest Exp Boost Rates:

gameserver.rate.regular.quest.exp_boost = 2
gameserver.rate.premium.quest.exp_boost = 2
gameserver.rate.vip.quest.exp_boost = 3

# 成长光环 5.1 / Aura Of Growth 5.1:
gameserver.rate.aura.of.growth.chance = 5

# 掉落倍率 / Drop Rates:

gameserver.rate.regular.drop = 1
gameserver.rate.premium.drop = 1
gameserver.rate.vip.drop = 1

# 亚特雷亚图鉴 / Atreian Bestiary:

gameserver.rate.regular.book = 2
gameserver.rate.premium.book = 2
gameserver.rate.vip.book = 2

# 怪物 HP/PW 倍率 / HP/PW Mobs Rates

gameserver.rate.normal.mobs.rate.hp = 1.0
gameserver.rate.normal.mobs.rate.pw = 1.0
gameserver.rate.elite.mobs.rate.hp = 1.0
gameserver.rate.elite.mobs.rate.pw = 1.0
gameserver.rate.hero.mobs.rate.hp = 1.0
gameserver.rate.hero.mobs.rate.pw = 1.0
gameserver.rate.legendary.mobs.rate.hp = 1.0
gameserver.rate.legendary.mobs.rate.pw = 1.0

# 伤害倍率 / Damage Multiplier Rates:

gameserver.damage.multiplier = 1.0

# PvP 经验倍率 / PvP XP Rates:

gameserver.rate.regular.xp.player.gain = 1
gameserver.rate.premium.xp.player.gain = 2
gameserver.rate.vip.xp.player.gain = 3

# PvP AP 倍率（玩家获得） / PvP AP Rates (Player Gain):

gameserver.rate.regular.ap.player.gain = 1
gameserver.rate.premium.ap.player.gain = 2
gameserver.rate.vip.ap.player.gain = 2

# PvP AP 倍率（玩家损失） / PvP AP Rates (Player Loss):

gameserver.rate.regular.ap.player.loss = 1
gameserver.rate.premium.ap.player.loss = 2
gameserver.rate.vip.ap.player.loss = 2

# PvE AP 倍率 / PvE AP Rates:

gameserver.rate.regular.ap.npc = 1
gameserver.rate.premium.ap.npc = 1
gameserver.rate.vip.ap.npc = 1

# PvE DP 倍率 / PvE DP Rates:

gameserver.rate.regular.dp.npc = 10
gameserver.rate.premium.dp.npc = 10
gameserver.rate.vip.dp.npc = 10

# PvP DP 倍率 / PvP DP Rates:

gameserver.rate.regular.dp.player = 1
gameserver.rate.premium.dp.player = 2
gameserver.rate.vip.dp.player = 2

# 钢铁之战奖励倍率 / Dredgion Reward Rates:

gameserver.rate.dredgion = 1

# PvP 孤独竞技场奖励倍率 / PvP Discipline Arena Reward Rates:

gameserver.rate.regular.pvparena.discipline = 1
gameserver.rate.premium.pvparena.discipline = 1
gameserver.rate.vip.pvparena.discipline = 1

# PvP 混沌竞技场奖励倍率 / PvP Chaos Arena Reward Rates:

gameserver.rate.regular.pvparena.chaos = 1
gameserver.rate.premium.pvparena.chaos = 1
gameserver.rate.vip.pvparena.chaos = 1

# PvP 合作竞技场奖励倍率 / PvP Harmony Arena Reward Rates:

gameserver.rate.regular.pvparena.harmony = 1
gameserver.rate.premium.pvparena.harmony = 1
gameserver.rate.vip.pvparena.harmony = 1

# PvP 荣耀竞技场奖励倍率 / PvP Glory Arena Reward Rates:

gameserver.rate.regular.pvparena.glory = 1
gameserver.rate.premium.pvparena.glory = 1
gameserver.rate.vip.pvparena.glory = 1
