# 基础攻城配置:
# Basic siege config's:

# 启用攻城系统
# Enable siege system
# 默认值: true / Default: true
gameserver.siege.enable = true

# 击杀领主的勋章倍率
# Amount medal rate for lords kill
# 默认值: 1 / Default: 1
gameserver.siege.medal.rate = 1

# 启用攻城护盾
# Enable siege shield
# 默认值: true / Default: true
gameserver.siege.shield.enable = true

# 启用自动龙族突袭
# Enable automatic Balaur Assaults
gameserver.siege.assault.enable = false

# 龙族突袭概率倍率（浮点数）
# Rate for Balaur assaults chance(float)
# 默认值: 1 / Default: 1
gameserver.siege.assault.rate = 1

# 自动攻城
# AUTOMATIC SIEGE

# 启用/禁用自动“攻城”
# Enable/Disable automatic "SIEGE"
# 默认值: false / Default: false
gameserver.auto.siege.race = false

# 自动“攻城”要塞 ID
# Automatic "SIEGE "Fortress ID"
gameserver.auto.siege.id = 1131,1132;1141,2011;2021,3011;3021
