# 线程相关配置:
# Thread config's:

# 注意：若不清楚此设置的作用，请勿修改！
# NOTE: If you don't know what this setting does, please don't change it!

# 每个核心同时处理的线程数
# Threads handled by each core at once
# 英特尔 Core i7、i5、i3 系列每个核心可处理 2 个线程。
# Intel's Core i7, i5, and i3 series can handle 2 threads per core.
# AMD 的 Athlon、Phenom、Sempron、Opteron 芯片使用每核心 1 线程模型。
# AMD's Athon, Phenom, Sempron, and Opteron chips, use a 1-thread-per-core model.
# SPARC Niagara 系列服务器每个核心可处理 8 到 16 个线程。
# SPARC Niagara series of servers can handled anywhere from 8 to 16 threads per core.
# 默认值: 1 / Default: 1
gameserver.thread.basepoolsize = 2

# 默认值: 4 / Default: 4
gameserver.thread.threadpercore = 4

# 仅作为警告阈值。
# That's only a warning.
# 默认值: 5000 / Default: 5000
gameserver.thread.runtime = 60000

# 为即时线程池使用更高的线程优先级
# Use higher thread priorities for instant thread pool
# 注意：在 Linux 上必须以 root 运行，并使用参数：-XX:+UseThreadPriorities -XX:ThreadPriorityPolicy=1
# Note: in Linux you must be root and use switches: -XX:+UseThreadPriorities -XX:ThreadPriorityPolicy=1
# 默认值: false / Default: false
gameserver.thread.usepriority = true
