package com.aionemu.gameserver.model.account;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

import com.aionemu.gameserver.model.Race;
import com.aionemu.gameserver.model.items.storage.Storage;
import lombok.Getter;
import lombok.Setter;
import lombok.RequiredArgsConstructor;

/**
 * 账号模型。
 * Account model.
 *
 * @author SoulKeeper
 * @modified cura
 */
@Getter
@Setter
@RequiredArgsConstructor
public class Account implements Iterable<PlayerAccountData> {

	/** 本账号唯一 ID（由登录服务器生成）。 / Unique id of this account (it's generated by login server) */
	private final int id;
	/** 账号唯一名称 / Unique name of this account */
	private String name;
	/**
	 * 访问等级。
	 * Access level
	 */
	private byte accessLevel;
	/**
	 * 账号会员等级。
	 * Membership of this account
	 */
	private byte membership;

	/** 获取账号时间。 / Returns the account time. */
	private AccountTime accountTime;

	private final Map<Integer, PlayerAccountData> players = new HashMap<>();

	/**
	 * @return 账号仓库 / the accountWarehouse
	 */
	private Storage accountWarehouse;

	private int numberOfAsmos = 0;

	private int numberOfElyos = 0;

	private CharacterPasskey characterPasskey;

	/** 获取安全令牌。 / Returns the security token. */
	private String securityToken = "";

	private long tollCount;
	private long lunaCount;
	private byte vipLevel;
	private long vipExp;
	/** Unix seconds VIP end time. */
	private long vipExpireTime;

	/** Remaining VIP seconds; 0 if expired/inactive. expire_time==0 = permanent. */
	public int getVipRemainingSeconds() {
		if (vipLevel <= 0) {
			return 0;
		}
		if (vipExpireTime <= 0) {
			// 永久 / 未设过期时间——仍需为战斗通行证时长保留较大余量。 / permanent / unset expiry — still need a large remaining for BM duration
			return Integer.MAX_VALUE;
		}
		long remain = vipExpireTime - (System.currentTimeMillis() / 1000L);
		if (remain <= 0) {
			return 0;
		}
		return remain > Integer.MAX_VALUE ? Integer.MAX_VALUE : (int) remain;
	}

	/** 是否相等。 / Equality check. */
	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}

		if (!(o instanceof Account account)) {
			return false;
		}

		return id == account.id;
	}

	/** 返回哈希码。 / Returns hash code. */
	@Override
	public int hashCode() {
		return id;
	}

	/**
	 * @param chaOid
	 * @return PlayerAccountData
	 */
	public PlayerAccountData getPlayerAccountData(int chaOid) {
		return players.get(chaOid);
	}

	/**
	 * @param accPlData
	 */
	public void addPlayerAccountData(PlayerAccountData accPlData) {
		players.put(accPlData.getPlayerCommonData().getPlayerObjId(), accPlData);
		switch (accPlData.getPlayerCommonData().getRace()) {
		case ASMODIANS:
			numberOfAsmos++;
			break;
		case ELYOS:
			numberOfElyos++;
			break;
		}
	}

	/**
	 * @return 角色密保 / the characterPasskey
	 */
	public CharacterPasskey getCharacterPasskey() {
		if (characterPasskey == null) {
			characterPasskey = new CharacterPasskey();
		}
		return characterPasskey;
	}

	/**
	 * 返回该账号下的角色数量。
	 * Returns the number of players that are on this account
	 */
	public int size() {
		return players.size();
	}

	/**
	 * 按最后上线时间对账号排序。
	 * Sorts the accounts on last online
	 */
	public ArrayList<PlayerAccountData> getSortedAccountsList() {
		ArrayList<PlayerAccountData> list = new ArrayList<>();
		list.addAll(players.values());
		Collections.sort(list, new Comparator<>() {

			/**
			 * 比较 / compare.
			 */
			@Override
			public int compare(PlayerAccountData x, PlayerAccountData y) {
				Timestamp t1 = x.getPlayerCommonData().getLastOnline();
				Timestamp t2 = y.getPlayerCommonData().getLastOnline();
				if (t2 == null) {
					return 1;
				} else if (t1 == null) {
					return -1;
				}
				return y.getPlayerCommonData().getLastOnline().compareTo(x.getPlayerCommonData().getLastOnline());
			}
		});
		return list;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Iterator<PlayerAccountData> iterator() {
		return players.values().iterator();
	}

	/** 返回 number of / Returns the number of */
	public int getNumberOf(Race race) {
		return switch (race) {
			case ASMODIANS -> numberOfAsmos;
			case ELYOS -> numberOfElyos;
			default -> 0;
		};
	}

	/** Decrement 次数 / Decrement Count Of */
	public void decrementCountOf(Race race) {
		switch (race) {
		case ASMODIANS:
			numberOfAsmos--;
			break;
		case ELYOS:
			numberOfElyos--;
			break;
		}
	}

	/** 设置点数。 / Sets the toll. */
	public void setToll(long toll) {
		tollCount = toll;
	}

	/** 获取点数。 / Returns the toll. */
	public long getToll() {
		return tollCount;
	}

	/** 设置月华。 / Sets the luna. */
	public void setLuna(long luna) {
		lunaCount = luna;
	}

	/** 获取月华。 / Returns the luna. */
	public long getLuna() {
		return lunaCount;
	}

	/** 是否为空。 / Whether Empty. */
	public boolean isEmpty() {
		return numberOfAsmos == 0 && numberOfElyos == 0;
	}

	/** 返回最大玩家等级 / Returns the max player level*/
	public int getMaxPlayerLevel() {
		int maxLevel = 1;
		for (PlayerAccountData pad : players.values()) {
			if (pad.getPlayerCommonData().getLevel() > maxLevel) {
				maxLevel = pad.getPlayerCommonData().getLevel();
			}
		}
		return maxLevel;
	}

	/** 返回字符串表示。 / Returns string representation. */
	@Override
	public String toString() {
		return "Account [id=" + id + ", name=" + name + "]";
	}
}
