# 开发者配置 / Developer Config's:

# 启用刷怪 / Enable spawns
# 默认值: true / Default: true
# 若为 false，则不加载任何刷怪 / if false - not spawns will be loaded
gameserver.developer.spawn.enable = true

# 若设置，则为带随机加成的物品添加指定属性加成
# if set, adds specified stat bonus for items with random bonuses
gameserver.developer.itemstat.id = 0

# 检查刷怪点 / Check spawns
# 默认值: false / Default: false
# 若为 true，检查刷怪点是否位于未知区域外 / if true - checks spawns being outside any known zones
gameserver.developer.spawn.check = false

# 数据包处理设置 / Packets Proccessing Settings

# 仅对开发者显示数据包名称（仅控制台窗口）
# Display Packets Name for Developers only (Only Console Window)
# 默认值: false / Default: false
gameserver.developer.showpackets.enable = false

# 在聊天窗口显示数据包名称或十六进制字节
# Display Packets Name or Hex-Bytes in Chat Window
# 默认值: false / Default: false
gameserver.developer.show.packetnames.inchat.enable = false
gameserver.developer.show.packetbytes.inchat.enable = false

# 聊天窗口应显示的数据包总字节数？
# Total Packet Bytes should be shown in Chat Window?
# 默认值: 200 个十六进制字节 / Default: 200-Hexed bytes
gameserver.developer.show.packetbytes.inchat.total = 200

# 过滤哪些数据包应显示在聊天窗口？
# Filters which Packets should be shown in Chat Windows?
# 默认值: *（显示全部数据包） / Default: * (All Packets Shown)
# 例如 / e.g.  SM_MOVE, CM_CASTSPELL, CM_ATTACK
gameserver.developer.filter.packets.inchat = *

# 当玩家权限等级满足时，在聊天窗口显示数据包名称或十六进制字节
# if the Player Access Level is meet, display Packets-Name or Hex-Bytes in Chat Window
# 提示：建议玩家权限等级高于 3 / Tip: Player Access-Level higher than 3 is recommended
#
#  5 - 管理员 / Admin
#  4 - 首席GM / Head-GM
#  3 - GM
#  2 - 初级GM / Jr-GM
#  1 - 客服 / Support
#  0 - 玩家 / Player
#
gameserver.developer.show.packets.inchat.accesslevel = 3
