# 本文件包含管理员命令设置 / This file contains settings for admin commands
# 命令权限掩码 / Command masks:
#
#  5 - 管理员 / Admin
#  4 - 首席GM / Head-GM
#  3 - GM
#  2 - 初级GM / Jr-GM
#  1 - 客服 / Support
#  0 - 玩家 / Player
#

# GM 面板配置 / GM PANEL Config's:

#
# 技能面板 / SKILL PANEL
# 默认值: 3 / Default: 3
gameserver.administration.skilpanel = 3

# 开始任务 / START QUEST
# 默认值: 3 / Default: 3
gameserver.administration.startquestpanel = 3

# 删除任务 / DELETE QUEST
# 默认值: 3 / Default: 3
gameserver.administration.delquestpanel = 3

# 结束任务 / END QUEST
# 默认值: 3 / Default: 3
gameserver.administration.endquestpanel = 3

# 给予称号 / GIVE TITLE
# 默认值: 3 / Default: 3
gameserver.administration.givetitlepanel = 3
