# 登录服务器配置 / Login-server configuration

# 是否自动创建账号？ / Create accounts automatically or not?
loginserver.accounts.autocreate = true

# 设置服务器是否处于维护模式 / 仅 GM 可登录
# Set if the server is in maintenance or not / only gm can login
loginserver.server.maintenance = false

# 维护模式下的 GM 等级要求（默认值: 3）
# Set gm level for maintenance mode(Default 3)
loginserver.server.maintenance.gmlevel = 3

# 启用/禁用来自同一 IP 的账号登录洪水保护
# Enable\disable flood protector from 1 ip on account login
loginserver.server.floodprotector = true
loginserver.server.bruteforceprotector = true

# 检查游戏服务器是否仍然存活 / Checking gs if it still alive
loginserver.server.pingpong = true
loginserver.server.pingpong.delay = 3000

# 排除在洪水保护之外的 IP / Ip's excluded from flood protection
loginserver.excluded.ips =
