# ----------------------------
# 聊天服务器配置 / Chat Server Config's:
# ----------------------------

# 聊天服务器监听连接的地址
# CS will listen for connections on specified address
# 需为正式服的外部 IP / need to be your external Ip of your Live server
chatserver.network.client.address = 127.0.0.1:10241

# 聊天服务器监听游戏服务器连接的地址
# Address that will be used by CS to listen for GS connections
chatserver.network.gameserver.address = 127.0.0.1:9021

# 游戏服务器成功认证所需匹配的密码
# Password to match for successful authentication of the game server
# 注意：别忘了设置你的密码！ / NOTE: Don't forget to add your password!
chatserver.network.gameserver.password = aion

# 记录客户端的每个频道请求（调试用）
# log each channel request from client (debug purposes)
chatserver.log.channel.request = true

# 记录对无效频道的请求（调试用）
# Log requests to invalid channels (debug purposes)
chatserver.log.channel.invalid = true

# 是否记录聊天？ / Log chat?
chatserver.log.chat = true

# 聊天语言 / Lang Chat
# 1 = 英语 / English		7 = 瑞典语 / Swedish
# 2 = 法语 / French		8 = 芬兰语 / Finnish
# 3 = 德语 / German		9 = 挪威语 / Norwegian
# 4 = 意大利语 / Italian		10 = 希腊语 / Greek
# 5 = 西班牙语 / Spanish
# 6 = 丹麦语 / Danish
chatserver.chat.lang = 3

# 消息间隔（秒）。0 为禁用 / delay between messages. seconds. 0 to disable
# 强烈建议启用 / strongly recommended
chatserver.chat.message.delay = 30

# 指定聊天服务器重启频率 / Specifies the frequency the chat server will be restarted
# 选项: NEVER, DAILY, WEEKLY, MONTHLY / Options: NEVER, DAILY, WEEKLY, MONTHLY
# 默认值: NEVER / Default: NEVER
chatserver.restart.frequency = NEVER

# 指定服务器应在每天的具体时间重启（当然需遵循频率设置）
# Specifies the exact time of day the server should be restarted (of course respecting the frequency)
# 默认值: 5:00 / Default: 5:00
chatserver.restart.time = 5:00
