# ----------------------------
# 数据库配置 / Database Config's:
# ----------------------------

# 连接数据库时使用的数据库驱动类
# This class represents database driver class that will be used while connecting to database
database.driver = com.mysql.cj.jdbc.Driver

# 数据库连接 URL / This is database url.
database.url = jdbc:mysql://127.0.0.1:3306/al_server_ls?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC

# 数据库用户 / Database user
database.user = root

# 数据库密码 / Database password
# 注意：请修改此项！Root 密码不安全！ / NOTE: Change this! Root password is not safe!
database.password = 123456

database.maxconnections = 20
database.hikari.maxLifetime = 600000
database.hikari.connectionTestQuery = SELECT 1
