# ----------------------------
# 网络配置 / Network Config's:
# ----------------------------

# 登录服务器监听连接的端口 / LoginServer will listen for connections on specified port
loginserver.network.client.port = 2106

# 登录服务器绑定的网络接口 / LoginServer will bind specified network interface
# * - 绑定所有接口 / bind all interfaces
loginserver.network.client.host = *

# 玩家可尝试登录的次数，超过后因暴力破解被封禁
# How many times player can try to login before he get's banned for bruteforcing
loginserver.network.client.logintrybeforeban = 5

# 因暴力破解被封禁的时长（分钟）
# For what time in minutes player should be banned in case of bruteforcing
loginserver.network.client.bantimeforbruteforcing = 15

# 登录服务器监听游戏服务器连接的主机地址
# Host that will be used by LS to listen for GS connections
loginserver.network.gameserver.host = *

# 登录服务器监听游戏服务器连接的端口
# Port that will be used by LS to listen for GS connections
loginserver.network.gameserver.port = 9014

# 是否自动创建账号？ / Create accounts automatically or not?
loginserver.accounts.autocreate = true

# 设置服务器是否处于维护模式 / 仅 GM 可登录
# Set if the server is in maintenance or not / only gm can login
loginserver.server.maintenance = false

# 维护模式下的 GM 等级要求（默认值: 3）
# Set gm level for maintenance mode(Default 3)
loginserver.server.maintenance.gmlevel = 3

# 启用/禁用来自同一 IP 的账号登录洪水保护
# Enable\disable flood protector from 1 ip on account login
loginserver.server.floodprotector = true
loginserver.server.bruteforceprotector = true

# 检查游戏服务器是否仍然存活 / Checking gs if it still alive
loginserver.server.pingpong = true
loginserver.server.pingpong.delay = 3000

# 洪水管理器 / flood manager
# 合法重连时间。若更快则封禁 loginserver.network.client.bantimeforbruteforcing 分钟
# legal reconnection time. if faster - ban for loginserver.network.client.bantimeforbruteforcing min
# 单位：秒 / seconds
network.fastreconnection.time = 5

# 排除在洪水保护之外的 IP / Ip's excluded from flood protection
loginserver.excluded.ips =
